### ISSUE TITLE
0 coverage on a Gentoo Hardened system (with grsecurity)

### ISSUE THREAD

**Issue by Feandil** [SimonKagstrom/kcov#100]
I'm unable to get any coverage on my gentoo hardened system.
With a "normal" kcov, no error nor warning at all.
After setting g_kcov_debug_mask to 0xffff, I get the following:
```
PT forked 30549
PT continuing 30549 with signal 0
PT stopped PID 30549 0x0000057f
PT BP at 0x3de29485b1b:-1 for 30549
Can't find breakpoint at 0x3de29485b1b
main file relocation = 0x732d138000
BP registered at 0x732d148e00
REPORT /var/tmp/portage/dev-lang/rust-1.0.0/work/rustc-1.0.0/src/libcore/fmt/mod.rs:657 at 0x732d148e00
BP registered at 0x732d148e47
REPORT /var/tmp/portage/dev-lang/rust-1.0.0/work/rustc-1.0.0/src/libcore/fmt/mod.rs:658 at 0x732d148e47
[... lots of successfull BP registered/ REPORT ...]
BP registered at 0x732d14ab10
REPORT /home/feandil/test/maillog/src/parser/postfix/inner.rs:6 at 0x732d14ab10
REPORT /home/feandil/test/maillog/src/parser/postfix/inner.rs:6 at 0x61aece5e7
REPORT /home/feandil/test/maillog/src/parser/postfix/inner.rs:6 at 0x61aece5e7
BP registered at 0x732d14abf9
REPORT /home/feandil/test/maillog/src/parser/postfix/inner.rs:8 at 0x732d14abf9
REPORT /home/feandil/test/maillog/src/parser/postfix/inner.rs:8 at 0x81aece5e7
REPORT /home/feandil/test/maillog/src/parser/postfix/inner.rs:8 at 0x81aece5e7
[... lots of successfull BP registered/ REPORT ...]
BP registered at 0x45155742890
REPORT /tmp/portage/sys-libs/glibc-2.20-r2/work/glibc-2.20/csu/../sysdeps/x86_64/crtn.S:45 at 0x45155742890
PT continuing 30549 with signal 0
PT stopped PID 30549 0x0003057f
PT BP at 0x3de289912f0:-1 for 30549
Can't find breakpoint at 0x3de289912f0
PT continuing 30549 with signal 0
PT stopped PID 30549 0x0003057f
PT BP at 0x3de289912f0:-1 for 30549
Can't find breakpoint at 0x3de289912f0
PT continuing 30549 with signal 0
PT stopped PID 30551 0x0000137f
PT BP at 0x3de289912f0:-1 for 30551
Can't find breakpoint at 0x3de289912f0
PT continuing 30551 with signal 0
PT stopped PID 30549 0x0003057f
PT BP at 0x3de289912f0:-1 for 30549
Can't find breakpoint at 0x3de289912f0
```

Any idea ? (I can help debugging)

**Comment by SimonKagstrom** [comment]
No immediate idea. But this being a rust program, perhaps it can be related to PIE executables and address randomization (perhaps the hardened gentoo enforces it strictly?). If you look in ptrace.cc, you'll see that kcov tries to disable address space randomization via the personality call (added by @lifthrasiir). Does this succeed in your case?

You could also try compiling a trivial program as a PIE executable (-g -fpie -fPIE, and link with -pie) and see if that works (to reduce the problem a bit).

**Comment by Feandil** [comment]
Sorry, I should have thought a bit more before opening this bug.
This is definitely a PaX issue, so now I've started playing with pax-mark on my executable:
- The default flags, PeMRS (everything enabled, except EMUTRAMP): 0 coverage
- PeMrS (everything enabled, except EMUTRAMP and RANDMMAP): 0 coverage
- PemRS (everything enabled, except EMUTRAMP and MPROTECT): correct coverage.

I'm more than surprised by this, I would have expected RANDMMAP (https://pax.grsecurity.net/docs/randmmap.txt) to be the reason for the failure, not MPROTECT (https://pax.grsecurity.net/docs/mprotect.txt)... I'll try to find more... (I'm starting to wonder if it's not rust that try some dark magic to go around the mprotect restriction -_-)

I think I should close this issue: it's not really a problem in this software and I have a solution....

BTW, even if it "works" for the coverage, there are quite some errors:
```
PT error for 3896: -1
PT stopped PID 3895 0x00000000
PT exit 0 at 0xffffffffffffffff for 3895
PT continuing 3895 with signal 0
PT error for 3895: -1
PT stopped PID 3852 0x0000057f
PT BP at 0x175fc8ce33:-1 for 3852
REPORT hit at 0x175fc8ce33
PT continuing 3852 with signal 0
```

**Comment by SimonKagstrom** [comment]
At least some of the ptrace errors are "normal" (i.e., how ptrace behaves when a process exits). Ptrace is a strange beast.

Anyway, perhaps the MPROTECT stuff interfers with ptrace? Perhaps there is some special thing gdb does with PaX to be able to insert breakpoints even with MPROTECT?
