### ISSUE TITLE
HTML output should say "Javascript required" in red letters by default

### ISSUE THREAD

**Issue by apoelstra** [SimonKagstrom/kcov#103]
Users with noscript will see kcov output which is entirely unpopulated with "???" in every field. This can be very hard to debug since "my browser" is not the first place I'd think to check when trying to understand faulty coverage analysis with no error output anywhere).

I think the HTML output should say "Javascript is required to see all the test output".

**Comment by SimonKagstrom** [comment]
Fixed with c196d62.

As you can guess, I'm not so savvy with HTML and JavaScript!

**Comment by apoelstra** [comment]
Awesome, thanks for the quick response!
