### ISSUE TITLE
snmpd coverage only shows main function (snmpd.c)

### ISSUE THREAD

**Issue by VincentGibert** [SimonKagstrom/kcov#104]

**Comment by SimonKagstrom** [comment]
What version are you using? There was a bug quite some time ago that could
cause hanging execution.

**Comment by VincentGibert** [comment]
Hello SimonKagstrom

I try to do coverage with kcov v27 on a library used through snmpd, on a CentOS 6.6 system.
I therefore have installed all debuginfo needed by net-snmp, compiled with -g and then launched snmpd directly with kcov.
Once the agent started, I did a bunch of snmpwalk commands in order to get snmpd doing something
Then I stopped the service and check the coverage.

It only shows the snmpd.c coverage, as if it did not have followed the fork of the child.

**Comment by VincentGibert** [comment]
I tried using the --pid option to attach kcov, once snmpd started, but it is even worse.
I have no results at all using this. Maybe I did stg wrong.

**Comment by VincentGibert** [comment]
I saw that you covered a similar subject in issue #31 so I dont know what is going on here.

**Comment by SimonKagstrom** [comment]
The problem in Issue #31 was a fix to --pid issues, but should not be the problem in your case.

I don't really know what's happening in this case, forking is quite a common thing and should be handled well by kcov. snmpd doesn't exec another process after the fork?

A thing you can try is to just look at a file which you know is executed by snmpd (but not covered), and run kcov with the debug option, i.e.,

```
kcov --include-pattern=executed-file.c --debug=15 /tmp/kcov <snmpd>
```

then you should be able to see breakpoints that kcov sets up.

**Comment by VincentGibert** [comment]
Hi,
First of all, thank you for the answer.

As you suggested, I tried this : 
<code>kcov /tmp/KCOV_RESULTS --include-pattern=/usr/src/debug/net-snmp-5.5/agent/snmp_agent.c --debug=15 /usr/sbin/snmpd</code>

I know for sure that this file is executed, as gdb shows it to me when debugging snmpd (and I also know through the same process that my own lib is called)

The debug info is the folowwing : 
<i>PT forked 64536 
PT continuing 64536 with signal 0
PT stopped PID 64536 0x0000057f
PT BP at 0x7ffff77d4edb:-1 for 64536
Can't find breakpoint at 0x7ffff77d4edb
main file relocation = 0x7ffff7ff8000
PT continuing 64536 with signal 0
PT stopped PID 64536 0x0000057f
PT BP at 0x7ffff77d4edb:-1 for 64536
Can't find breakpoint at 0x7ffff77d4edb
main file relocation = 0x7ffff7ff8000
PT continuing 64536 with signal 0
PT stopped PID 64536 0x0000057f
PT BP at 0x7ffff77d4edb:-1 for 64536
Can't find breakpoint at 0x7ffff77d4edb
main file relocation = 0x7ffff7ff8000
PT continuing 64536 with signal 0
PT stopped PID 64536 0x0000057f
PT BP at 0x7ffff77d4edb:-1 for 64536
Can't find breakpoint at 0x7ffff77d4edb
main file relocation = 0x7ffff7ff8000
</i> 
and so on

I compared using this line : 
<code>kcov /tmp/KCOV_RESULTS --include-pattern=/usr/src/debug/net-snmp-5.5/agent/snmpd.c --debug=15 /usr/sbin/snmpd</code>

An with this, I can see that BP are indeed reached, and hit counted : 
<i>PT forked 64658
PT continuing 64658 with signal 0
PT stopped PID 64658 0x0000057f
PT BP at 0x7ffff77d4edb:-1 for 64658
Can't find breakpoint at 0x7ffff77d4edb
main file relocation = 0x7ffff7ff8000
BP registered at 0x7ffff7ffaecc
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:262 at 0x7ffff7ffaecc
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:262 at 0x1064538e39d
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:262 at 0x1064538e39d
BP registered at 0x7ffff7ffaed8
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:268 at 0x7ffff7ffaed8
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:268 at 0x10c4538e39d
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:268 at 0x10c4538e39d
BP registered at 0x7ffff7ffaef3
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:270 at 0x7ffff7ffaef3
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:270 at 0x10e4538e39d
REPORT /usr/src/debug/net-snmp-5.5/agent/snmpd.c:270 at 0x10e4538e39d
</i>
and so on.

Does that give you any clue ?

**Comment by SimonKagstrom** [comment]
Well, it seems like it doesn't even try to set breakpoints in that case, which is strange - almost like it doesn't find the source files in the debuginfo.

Does it behave the same way if you run snmpd with -f (i.e., without forking - I think it's -f from looking at the source file)?

And in this case, the debuginfo is in separate files via build-id? (I.e., not in the snmpd binary itself)

**Comment by SimonKagstrom** [comment]
OK, I've tried reproducing this on Fedora 21 (which I run) via the installed debuginfo files, and at least here I think it's a problem in how the net-snmp build generates the debug info. Looking at the build-id debug file, I see only the snmpd.c source file plus some system headers:

```
readelf --debug-dump=decodedline /usr/lib/debug/.build-id/e0/a180fcb5e3e4768daa907e5ad10129ec14164e.debug
CU: ./snmpd.c:
File name                            Line number    Starting address
snmpd.c                                      360              0x4ba0
snmpd.c                                      364              0x4ba0
[...]
/usr/include/bits/stdio2.h:
stdio2.h                                     104              0x4c39
```

Could you try the same on your system? The build-id file can be found via running "file /usr/sbin/snmpd".


And if this is the case, then the problem really lies within the snmpd build.

Anyway, while debugging this, I found a regression with the handling of --skip-solibs, which was fixed in 5b6ec70df800bebdbf21279cfa7d6866b3ffd7f0. Should not affect what you are seeing though.

**Comment by VincentGibert** [comment]
Again, many thanks for answering so quickly.
I will try the same on my system and let you know asap.

**Comment by VincentGibert** [comment]
I have run some tests, here are the results : 
1 : it behaves the same if I run snmpd with -f option
2 : the debuginfo is indeed in a separate  file via build-id. I tried compiling snmpd to a non stripped binary, but the behavior is, again, the same
3 : I looked at the build-id of snmpd using this on my system : 

    readelf --debug-dump=decodedline /usr/lib/debug/.build-id/5d/b2f35141e8e29426b725d0ae94ec9cfb5e106a.debug

The output is very similar to what you got on Fedora 21, but without the system headers : 

    CU: /usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/snmpd.c:
    File name                            Line number    Starting address
    snmpd.c                                      262              0x2ecc

    snmpd.c                                      268              0x2ed8
    snmpd.c                                      270              0x2ef3
    [...]
    snmpd.c                                     1315              0x5745

But I am not sure I really get why this is a problem, as I got a similar output with <i>snmpwalk</i> , which behaves correctly with kcov : 

    readelf --debug-dump=decodedline /usr/lib/debug/.build-id/c1/05050771129e4b77a0058c7a9fb1a0345c0d71.debug
    CU: /usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/snmpwalk.c:
    File name                            Line number    Starting address
    snmpwalk.c                                    87            0x401014

    snmpwalk.c                                    88            0x401018
    snmpwalk.c                                    89            0x40104
    [...]
    snmpwalk.c                                   419            0x401d74

**Comment by SimonKagstrom** [comment]
OK, I've debugged this a bit further, and I believe it's got something to do with shared libraries. I've built the net-snmp source code in a Debian chroot, and in that, I can see the snmp_agent.c coverage when running with

```
kcov --include-pattern=snmp_agent.c /tmp/kcov snmpd
```

but not if I run without shared libraries:

```
kcov --skip-solibs --include-pattern=snmp_agent.c /tmp/kcov snmpd
```

so snmp_agent.c is probably in one of the shared libraries. I think it might be that kcov doesn't handle build-info correctly for shared libraries, but I'll have to investigate this further.

**Comment by VincentGibert** [comment]
Thanks for the answer. snmp_agent.c is indeed in a shared library : libnetsnmp.so.20.

But I don't understand how building the net-snmp source code allowed you to see coverage into snmp-agent.c, as I did the same test with no success.
I built it in a CentOS chroot, but executed it on the same environment than previously, maybe that could cause the behavior to differ ?

**Comment by SimonKagstrom** [comment]
Hmm... Perhaps so, I built it under a Debian chroot.

I'll try to build it on Fedora and see how it behaves there. However, I'm slightly short on time now (and will be for the next couple of weeks), so I haven't really looked at this problem. Sorry about that, and thanks for being patient!

**Comment by VincentGibert** [comment]
I totally understand that, of course.
Thanks for your time, I'll let you know if I figure out a way to solve the problem in the meantime.

**Comment by SimonKagstrom** [comment]
I built it for Fedora 21, and with the source locally it works fine there, but not with the one installed on the system.

I think this points to a problem with build-ids for shared libraries and I've committed a possible fix (157d013 above), but I'm not sure if it's really the issue here. Also, I don't have the source at hand in my system, so it's untested. Care to test?

**Comment by VincentGibert** [comment]
Hi again,
I tried the latest git snapshot, including your last fix, and it works !
Not sure I get the "why" but it is a real relief.

Again, many thanks !

**Comment by SimonKagstrom** [comment]
Great!

This was probably a regression introduced with the PIE support. The ELF-parsing has some special cases for the first file (i.e., the actual program itself), and sets a flag after the first file has been parsed. However, in this case, the flag wasn't actually set - which caused the shared libraries to be handled incorrectly.

I'm closing and changing the heading to reflect the bug, once found. Thanks for the report!
