### ISSUE TITLE
Coverage reported to coveralls.io for rust binaries is always 0%

### ISSUE THREAD

**Issue by vberger** [SimonKagstrom/kcov#106]
Since recently, all my travis builds of rust applications report a coverage of 0% on coveralls.io.

However, if I run kcov locally on my computer the geenrated report is correct and monitors everything. But adding the ``--coveralls-id=...` flag to the command line uploads to coveralls a report of 0% covered.

See https://coveralls.io/github/vberger/silinapse : build number 8 was the last working build, number 9 was generated by travis and number 10 was generated from command-line by me on my computer.

**Comment by SimonKagstrom** [comment]
I think this is actually a coveralls issue, see

  https://github.com/lemurheavy/coveralls-public/issues/589

I can reproduce it as well, but without any kcov changes. Looking at the individual files in the coveralls interface, coverage looks correct - but the summary says 0%.

**Comment by SimonKagstrom** [comment]
This should have been the coveralls issue above, so closing.
