### ISSUE TITLE
kcov triggers false (I think) mem-leak report from clang address sanitizer

### ISSUE THREAD

**Issue by rollbear** [SimonKagstrom/kcov#113]
I've build the "compiling_tests.cpp" program for [Trompeloeil](https://github.com/rollbear/trompeloeil) with clang++3.6.2 and -fsanitizer=address,undefined (also tried with clang++ 3.7.0 rc3, built from sources.)

If I run the program stand alone, all is well. If I run it in kcov, address sanitizer reports a leak at exit.
This leak report does not appear when compiled with g++-4.9, 5.1 or 5.2, so it may be a clang++ issue.

**Comment by SimonKagstrom** [comment]
Can you try running kcov with the --skip-solibs parameter?

**Comment by rollbear** [comment]
The only difference I see when using --skip-solibs is that it runs 3 times faster. The reports are the same.

**Comment by SimonKagstrom** [comment]
Can't reproduce in Ubuntu 14.04 with clang++-3.6.0 at least - but I also had to patch the cstdio system header to get it building, and I get 31 failed test cases both with and without kcov.

**Comment by rollbear** [comment]
I presume the failed test cases are due to the c++ std lib used. If you used libstdc++ from g++ 4.8 or older, it doesn't support ``<regex>``, so all tests that depend on matching regular expressions fail. I'll try again when clang 3.7 is formally released.

**Comment by rollbear** [comment]
Revisited after a long time. The problem remains, but only when building with -fsanitize=address and with -fstdlib=libc++. Using stdlibc++ from g++ exposes no leak.

So, on the one hand it looks like a libc++ issue, but on the other hand the leak is only shown when run under kcov.

Tested with kcov commit 43b1e3a01b8bbedfc333ea2b7f1668873690757a

I have also reproduced this on Ubuntu 15.10 x86_64

**Comment by SimonKagstrom** [comment]
I also revisited this recently, but I unfortunately I haven't been able to use the address sanitizer with clang-3.7. With 3.5 I get the same leak both with and without kcov:

```
$ clang++-3.5 -fsanitize=address -std=c++14 -g -I Catch-1.2.1-develop.12/include -o self_test compiling_tests.cpp
$ ./self_test 
===============================================================================
All tests passed (257 assertions in 162 test cases)


=================================================================
==24649==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x60f38b (/lhome/simkag/private-devel/trompeloeil/self_test+0x60f38b)
    #1 0x781cfe (/lhome/simkag/private-devel/trompeloeil/self_test+0x781cfe)
    #2 0x852810 (/lhome/simkag/private-devel/trompeloeil/self_test+0x852810)
    #3 0x6aa26f (/lhome/simkag/private-devel/trompeloeil/self_test+0x6aa26f)
    #4 0x1249f91 (/lhome/simkag/private-devel/trompeloeil/self_test+0x1249f91)
    #5 0x1247c5e (/lhome/simkag/private-devel/trompeloeil/self_test+0x1247c5e)
    #6 0x982efc (/lhome/simkag/private-devel/trompeloeil/self_test+0x982efc)
    #7 0x6995a7 (/lhome/simkag/private-devel/trompeloeil/self_test+0x6995a7)
    #8 0x11636ca (/lhome/simkag/private-devel/trompeloeil/self_test+0x11636ca)
    #9 0x99e2ed (/lhome/simkag/private-devel/trompeloeil/self_test+0x99e2ed)
    #10 0x6d00a7 (/lhome/simkag/private-devel/trompeloeil/self_test+0x6d00a7)
    #11 0x7fdf78668ec4 (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
```

**Comment by rollbear** [comment]
I built the new clang 3.8RC1 from sources and retried on the same machine, and now all is good. I still get the issue with 3.7, but it is either something wonky with 3.7 itself, or (more likely) with my installation of it.

I do get this leak (regardless of kcov):

    #0 0x5150bb in operator new(unsigned long) /var/tmp/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:62:35
    #1 0x61f6d8 in (anonymous namespace)::____C_A_T_C_H____T_E_S_T____1724::test() /home/bjorn/devel/trompeloeil/compiling_tests.cpp:1730:15
    #2 0x7d43d5 in Catch::MethodTestCase<(anonymous namespace)::____C_A_T_C_H____T_E_S_T____1724>::invoke() const /home/bjorn/devel/trompeloeil/../Catch/include/internal/catch_test_registry.hpp:25:9
    #3 0x53052c in Catch::TestCase::invoke() const /home/bjorn/devel/trompeloeil/../Catch/include/internal/catch_test_case_info.hpp:176:9
    #4 0x8b7b07 in Catch::RunContext::invokeActiveTestCase() /home/bjorn/devel/trompeloeil/../Catch/include/internal/catch_run_context.hpp:309:13
    #5 0x8b5675 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/bjorn/devel/trompeloeil/../Catch/include/internal/catch_run_context.hpp:280:21
    #6 0x80d579 in Catch::RunContext::runTest(Catch::TestCase const&) /home/bjorn/devel/trompeloeil/../Catch/include/internal/catch_run_context.hpp:104:21
    #7 0x51d445 in Catch::runTests(Catch::Ptr<Catch::Config> const&) /home/bjorn/devel/trompeloeil/../Catch/include/internal/../catch_session.hpp:78:27
    #8 0x94a509 in Catch::Session::run() /home/bjorn/devel/trompeloeil/../Catch/include/internal/../catch_session.hpp:186:42
    #9 0x829120 in Catch::Session::run(int, char const* const*) /home/bjorn/devel/trompeloeil/../Catch/include/internal/../catch_session.hpp:165:30
    #10 0x55b124 in main /home/bjorn/devel/trompeloeil/../Catch/include/internal/catch_default_main.hpp:15:12
    #11 0x30084207af in __libc_start_main (/lib64/libc.so.6+0x30084207af)

That, however, is a known issue with Catch.
