### ISSUE TITLE
Big memory leak with shared memory

### ISSUE THREAD

**Issue by jbatmall** [SimonKagstrom/kcov#122]
Hi,

I have a big memory leak when I used a shared memory

#### Environnement
Operating system : centos 6.6 (kernel 2.6.32-504) x86_64

#### Reproduction
Reproduced with version 29 of kcov but the problem also occurs with the latest snapshot

### Report
I'm developing a dynamic shared library (.so) and snmpd (net-snmp daemon) use it.
This library created a many pthread and fork (about 20 pthread and 20 fork every 4 seconds) to collect data

But when I launched snmpd with kcov
```
kcov --include-path=/src_path /tmp/output /usr/sbin/snmpd -f -A -LS 0-5 0 -p /var/run/snmpd.pid -a
```
I have seen an increase in the memory used by kcov to saturation of memory (RAM and swap)
```
Tasks: 301 total,   2 running, 297 sleeping,   1 stopped,   1 zombie
Cpu(s):  0.3%us,  8.3%sy,  0.0%ni, 91.4%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  16221228k total, 16052524k used,   168704k free,   460020k buffers
Swap: 16777212k total,        0k used, 16777212k free,  4495416k cached

   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                          
110313 root      20   0 10.3g  10g 3860 R 99.5 65.8   1:20.93 kcov                                                                                                                                            
110081 root      20   0  172m  66m  40m S  0.0  0.4   0:07.05 Xorg                                                                                                                                             
111374 root      20   0  251m  28m  15m T  1.0  0.2   0:00.01 nvidia-settings                                                                                                                                  
110315 root      20   0  921m 9892 5804 S  0.0  0.1   0:00.16 snmpd                                                                                                                                            
 58305 root      20   0 98.1m 6412 3388 S  0.0  0.0   0:00.50 sshd                                                                                                                                             
  1806 haldaemo  20   0 39180 5692 4176 S  0.0  0.0   0:03.23 hald                                                                                                                                             
  6615 root      20   0 98368 4384 3388 S  0.0  0.0   0:00.43 sshd                                                                                                                                             
 48296 root      20   0 98368 4384 3388 S  0.0  0.0   0:00.18 sshd                                                                                                                                             
136879 root      20   0 98368 4384 3388 S  0.0  0.0   0:01.02 sshd                                                                                                                                             
132486 root      20   0 98368 4380 3388 S  0.0  0.0   0:00.83 sshd                                                                                                                                             
 80262 root      20   0 98368 4364 3388 S  0.0  0.0   0:12.86 sshd         
```

### Additional information
kcov reload one library many time (libnividia-glcore.so.346.47 - size 40Mo - used when I run nvidia-settings command for collect data)
but I think that this issues is not related to this lib

When running kcov with --debug=30, the following message appears:
```
PT stopped PID 118669 0x0000137f
PT BP at 0x7ffff70ceb1c:-1 for 118669
Can't find breakpoint at 0x7ffff70ceb1c
PT continuing 118669 with signal 0
PT stopped PID 118670 0x0000137f
PT BP at 0x7ffff70ceb1c:-1 for 118670
Can't find breakpoint at 0x7ffff70ceb1c
PT continuing 118670 with signal 0
PT stopped PID 118669 0x0000057f
PT BP at 0x7ffff7dddaff:-1 for 118669
Can't find breakpoint at 0x7ffff7dddaff
PT continuing 118669 with signal 0
PT stopped PID 118670 0x0000057f
PT BP at 0x7ffff7dddaff:-1 for 118670
Can't find breakpoint at 0x7ffff7dddaff
No debug symbols in /usr/lib64/libnvidia-glcore.so.346.47.
PT continuing 118670 with signal 0
PT stopped PID 118669 0x0000057f
PT BP at 0x7ffff77dbce9:-1 for 118669
Can't find breakpoint at 0x7ffff77dbce9
No debug symbols in /usr/lib64/libnvidia-glcore.so.346.47.
PT continuing 118669 with signal 0
PT stopped PID 118670 0x0000057f
PT BP at 0x7ffff77dbce9:-1 for 118670
Can't find breakpoint at 0x7ffff77db
```

#### Fix found
After looking the source code and conducting tests I found a fix that solves my problem but I'd like to have your opinion

In file "src/parsers/elf-parser.cc"

Function parseOneElf
```
			Segment seg(fileData + sh_offset, sh_addr, sh_addr, sh_size);
			// If we have segments already, we can safely skip this
			if (setupSegments)
				m_curSegments.push_back(seg);
			m_executableSegments.push_back(seg);
		}
		ret = true;
        free(fileData);  // MY FIX
out_elf_begin:
		elf_end(m_elf);
		return ret;
	}
```
##### Analysis

In file "src/parsers/elf-parser.cc"
m_executableSegments is an attribute of the class ElfInstance
```
817 : SegmentList_t m_executableSegments
```
where SegmentList_t is a std::vector<Segment> and Segment is a class (file src/include/file-parser.hh)

m_executableSegments is used in functions addressIsValid,parseOneElf and addFile

It's filled in function parseOneElf (src/parsers/elf-parser.cc)
```
			Segment seg(fileData + sh_offset, sh_addr, sh_addr, sh_size); 
			// If we have segments already, we can safely skip this
			if (setupSegments)
				m_curSegments.push_back(seg);
			m_executableSegments.push_back(seg);
```

For remember (file src/include/file-parser.hh)
```
			Segment(const void *data, uint64_t paddr, uint64_t vaddr, uint64_t size) :
				m_data(data), m_paddr(paddr), m_vaddr(vaddr), m_size(size)
			{
			}
```

In addFile (src/parsers/elf-parser.cc)
```
118 : m_executableSegments.clear();
```

Clear function calls the destructor of Segment Class
It destroys all Segments objects but can't destroy fileData (cf elf-parser.cc:475) because Segment class store only char* pointer (m_data)
fileData is an pointer created by "read_int" function (cf src/utils.cc)

### Conclusion

I'm not sure to my fix because the addressIsValid function (which use m_executableSegments) is called in parseOneDwarf

What are you thinking about ?

**Comment by SimonKagstrom** [comment]
Thanks for the detailed report, excellent analysis!

Anyway, you are correct about the memory leak, but I think it needs to be fixed by allocating and copying the data into the Segment class instead (like you hinted). Freeing the fileData in parseOneElf() will cause accesses of freed memory when parseOneDwarf.

Send a merge request if you get around to fixing it! I can do it otherwise, but it will probably take a while since I'm busy with other stuff right now. Also, since you identified the issue, it's better that your name is on the commit :-)

**Comment by SimonKagstrom** [comment]
Fixed in ed65939. Thanks again for the very well-written report!

**Comment by jbatmall** [comment]
Hi,

Thanks for your fix!

I checked it but it's not good

The sequence causing the bug:
-> collector.cc.::tick
--> solib-handler.cc::OnTick
---> solib-handler.cc::checkSolibData 
---------> elf-parser.cc::setMainFileRelocation
--------------> elf-parser.cc::doParse
--------------------> elf-parser.cc::parseOneElf --> add elf in m_executableSegments

This sequence is repeatly indefinitely

m_executableSegments is never empty and I see more 1000 items inside ==> It's my bug

I suspect a problem in :
- checkSolibData function when kcov calls setMainFileRelocation
- solibThreadParse function when unmarshal data

What are you thinking about ?

For remember 

```
bool setMainFileRelocation(unsigned long relocation)
	{
		kcov_debug(INFO_MSG, "main file relocation = %#lx\n", relocation);

		if (m_elfIsShared) {
			if (!doParse(relocation))
				return false;
		} else {
			// this situation is probably problematic, as we have already notified
			// segment informations to the listeners.
			if (relocation != 0) {
				warning("Got a static executable with relocation=%#lx, "
					"probably the trace wouldn't work.", relocation);
			}
		}

		return true;
	}

**Comment by SimonKagstrom** [comment]
OK, I'm reopening the issue.

Then the non-terminating loop should be the reason why you get the leak - apart from the actual leak you identified before.

**Comment by SimonKagstrom** [comment]
OK, I'm reopening the issue.

Then the non-terminating loop should be the reason why you get the leak - apart from the actual leak you identified before.

**Comment by SimonKagstrom** [comment]
OK, I'm reopening the issue.

Then the non-terminating loop should be the reason why you get the leak - apart from the actual leak you identified before.

**Comment by SimonKagstrom** [comment]
I'm not completely sure if this is the problem in you case, but 2baf24d should at least avoid calling setMainFileRelocation repeatedly. Leaving open until you've tested though!

Are you adding / removing shared libraries in a loop?

**Comment by jbatmall** [comment]
Hi,
Thanks for your prompt fixes!
I checked it and it's good now :-)
I don't have any leaks and I see a good coverage in my report!
I searched a solution but you're so faster ;)
Good job you can close this issue
Thanks again

**Comment by SimonKagstrom** [comment]
Great! I probably implemented the bug in the first place:-)
