### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by edge226** [SimonKagstrom/kcov#138]
Can we please be able to take the produced bcov.css file, modify it, input it back into kcov to be able to generate all resulting websites with a preferred color scheme?

**Comment by SimonKagstrom** [comment]
Thanks for your detailed reports!

Yes, this should be possible. However, as the list of options are starting to get quite long, I think it would be better to provide a way of setting configuration key=value pairs through a command line option. The CSS file is currently hard-coded, but it shouldn't be difficult to load a different file if needed.

**Comment by edge226** [comment]
However you choose to implement it is your choice. These are simply ideas and may not be the most optimal implementation.

**Comment by SimonKagstrom** [comment]
Fixed with 37bd9a7
