### ISSUE TITLE
Ability to edit the default index name?

### ISSUE THREAD

**Issue by edge226** [SimonKagstrom/kcov#140]
Can we get a quick shortcut that edits the index.json `var header = { "command" : "this", ... };` parameter.

I'm using a for loop to run tests on individual portions of library scripts.

```
for file in ./tests/*; do if [[ -f "$file" ]]; then filename=${file#./}; kcov ./coverage "$filename"; echo ""; fi; done
```

I really like how doing it this way gives almost flawless information on where the bash processes flowed on a per command basis as well as information on the overall file.

The only thing I do not like is that I would like to be able to rename the parameter above easily in order to be able to push this information to a website. Otherwise it shows the last script that was run on the system.

**Comment by edge226** [comment]
I noticed that this should also show the total coverage of the merged information at the top with the name change. Currently it shows all the last ran information.

**Comment by SimonKagstrom** [comment]
Fixed in 509e8c9, thanks for the report!

**Comment by edge226** [comment]
Awesome! Great response time and generally a positive experience. Will report more issues that I notice to help you make this tool the best it can be.

**Comment by SimonKagstrom** [comment]
Unfortunately, the response time is not always that quick, but thanks! :-)

**Comment by edge226** [comment]
Sometimes we're busy and that is understandable. I personally do most of my code in large chunks. I plan on mixing kcov with bats in order to do the coverage testing for the code I create for the project, Which is an OS building framework in bash BTW. So I'll be reporting all bash issues I see.

I will also be creating a bats unit testing framework for the important things that are installed that most things rely on within the core system to ensure when we upgrade a package it maintains the same functionality as the old package before we push it to the users.

The Code Coverage I can see will really help when I'm writing code to know whether it is optimized or not. Right now I've simply been timing the operation of the algorithms as a measure but knowing the numbers like this is going to be awesome in the future when I make additions.

**Comment by SimonKagstrom** [comment]
Nice to hear, seems like a cool project!

Beware of the new Issue #145 though: The current parser isn't really a parser, so some shell scripts will generate very strange results.

**Comment by edge226** [comment]
Yeah running through Bats tends to do this. I kind of work around it a little via making a script that runs the bats. This tends to cause kcov to completely miss that there was a bats file entirely and instead sees a /tmp/bats.#.src file. I exclude the path of /usr/lib/bats and essentially the /tmp/bats file takes over where the original bats file existed and contains most the same data.

I only use kcov to add some functionality and will probably simply add it onto the things I already do. Shellcheck will also be an important part to this entire code checking system.

What gotcha's may apply with this parser issue?

**Comment by SimonKagstrom** [comment]
There are a few other bugs for bash corner-cases in the issue tracker, so the bash parser is problematic.

kcov needs to know two things really: What lines are executable, and which are executed. For compiled programs, executableness comes via DWARF debug information. For Python and Bash scripts, the scripts need to be parsed for executableness first. Some lines are trivial (e.g., starting with # for comments), but bash in particular is tricky without a proper parser. E.g., HERE documents cause trouble (although it's mostly handled by kcov), and the reporting from bash when a line is executed is also sometimes not straight-forward (i.e., on another line than what's actually being executed).
