### ISSUE TITLE
Add support for Codecov

### ISSUE THREAD

**Issue by stevepeak** [SimonKagstrom/kcov#150]
Hey! Thank you for creating and maintaining this great tool.

I would love to see this integrated with Codecov. We have an example of this working at https://github.com/codecov/example-bash

Let me know if I may help out in any way. 👍 💯

**Comment by SimonKagstrom** [comment]
Thanks!

I'll take a look at this again! I started working on it, but got carried away with other things quite a while ago (it's issue #114). Anyway, thanks for the example, I'll look into it.

Closing this since it's a duplicate, but I'll continue with #114 instead.

**Comment by SimonKagstrom** [comment]
And I'm back already :-)

Is there anything in particular you'd like kcov to do for codecov? It seems like you're parsing cobertura.xml from the codecov.io/bash script, which seems to work well enough. What I had in mind in #114 was to integrate codecov via libcurl similar to how coveralls is handled, i.e., generate the codecov coverage-json and upload it directly from kcov. Would that be a better solution you think?

**Comment by stevepeak** [comment]
@SimonKagstrom Thank you for your time.

I notice that you have Coveralls integrated directly into kcov ([as seen here](https://github.com/SimonKagstrom/kcov#travis-ci--coveralls-integration)) I would still like to use the [codecov-bash](https://github.com/codecov/codecov-bash) uploader but have this integration mentioned in the read me. Codecov would like to try to have a single point of entry (the bash uploader) which provides a very clear way to integrate with us for *almost all* languages.

Perhaps changing the readme to mention 3rd party options.

**Comment by SimonKagstrom** [comment]
Fixed the README.md with 03a45a0. Let me know if it does/doesn't look OK to you!

**Comment by stevepeak** [comment]
Awesome 👍 thank you for everything!

PS you may be interested in https://github.com/codecov/example-bash/issues/5
