### ISSUE TITLE
Executing kcov in a docker image fails

### ISSUE THREAD

**Issue by Ragnaroek** [SimonKagstrom/kcov#151]
I'm currently trying to build a docker image for kcov (https://github.com/Ragnaroek/kcov_docker). Compiling from source works fine, but executing kcov on a RUST executable fails:

kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/trellis-c0ed8d40a93cd721
Can't set personality: Operation not permitted
kcov: error: Can't start/attach to target/debug/trellis-c0ed8d40a93cd721
Child hasn't stopped: ff00
kcov: error: Can't start/attach to target/debug/trellis-c0ed8d40a93cd721

Any hints what goes wrong here?

**Comment by SimonKagstrom** [comment]
Not sure, but perhaps it's similar to a travis fix I had to make for attaching to already running processes, 00b65c3c4f3fe45c7b1072fc3cf1ffa45e0a8e1d?

**Comment by SimonKagstrom** [comment]
Or actually, it's more likely related to this docker issue:

http://emacs.stackexchange.com/questions/22665/building-emacs-in-a-docker-container

kcov uses the personality syscall (to be able to run PIE executables without address space randomization), and it seems like docker is disabling personality().


Nice initiative by the way, I've been meaning to do something similar myself (Issue #115),  but still hasn't gotten round to it.

**Comment by Ragnaroek** [comment]
Well that was a good hint. Got it working now. The trick is to set the correct security settings like here:
docker run -it --rm --security-opt seccomp=unconfined -v $(pwd):/source kcov

I will add some more documentation to the repo and maybe we could publish the image on the docker hub?

**Comment by SimonKagstrom** [comment]
Good to hear that you got it working!

Publishing it on dockerhub sounds like a splendid idea, thanks for the
work! This would have taken me much more time since I'm not used to docker
yet.

**Comment by Ragnaroek** [comment]
And there is the "final" version:
https://github.com/Ragnaroek/kcov_docker

https://hub.docker.com/r/ragnaroek/kcov/

If you want I can you add you as a collaborator to the docker repository with full access.

I think this issue can now be closed?

**Comment by SimonKagstrom** [comment]
Yep, closing it!

Collaboratorness for me would be a bonus, although I'm not sure I'll contribute much in a while (still being a docker newbie).

Thanks for the very good work!

**Comment by Ragnaroek** [comment]
Ok, send me you dockerhub username and I will add you!

**Comment by SimonKagstrom** [comment]
I'll get back once I manage to login :-).
