### ISSUE TITLE
Build fail with default python

### ISSUE THREAD

**Issue by hngiang** [SimonKagstrom/kcov#155]
Following issue #86, i build fail, current my mac is macOS Sierra, which have python default path `/usr/bin/python` not python2, i installed `python3` have path `/usr/local/bin/python3`. So i confused we need to default path `/usr/bin/python`

**Comment by SimonKagstrom** [comment]
Ah, that's true.

I'll look into making a proper fix, i.e., making it compatible with both Python 2 and Python 3.

**Comment by hngiang** [comment]
Thanks @SimonKagstrom

**Comment by SimonKagstrom** [comment]
Fixed with bcf10c4.
