### ISSUE TITLE
show combined coverage

### ISSUE THREAD

**Issue by oliver** [SimonKagstrom/kcov#16]
Is it possible to display the combined coverage from running different applications? I have several unit test applications (small applications testing particular parts of the same API), and would like to see coverage info for the entire API after running all tests.

Currently the HTML report contains a a separate coverage report for each unit test application. I'd like to see a single report instead (or in addition to the separate reports).

**Comment by barsan-ds** [comment]
Is there a reference on the cli options to use in order to collect data from multiple executables and report only once?

**Comment by SimonKagstrom** [comment]
@barsan-ds if you run kcov with the same output directory for multiple programs, i.e.,

```
kcov /tmp/out program1
kcov /tmp/out program2
```

it will automatically create a `[merged]` section in the output. The other option is to merge multiple runs afterwards, where you use

```
kcov /tmp/out1 program1
kcov /tmp/out2 program2
kcov --merge /tmp/out /tmp/out1 /tmp/out2
```

it's described in the manual page and with `--help`, but I guess it could be a good idea to add more info to the github README file, which is probably easier to access for most people these days!
