### ISSUE TITLE
Installing on OSX, kcov can't find LLDB

### ISSUE THREAD

**Issue by MasonRemaley** [SimonKagstrom/kcov#166]
I'm trying to install kcov on OSX, but I've run into some problems. I followed the installation instructions, but when I run kcov I get this error:

```
dyld: Library not loaded: @rpath/LLDB.framework/LLDB
  Referenced from: /usr/local/bin/kcov
  Reason: image not found
Abort trap: 6
```

I have lldb version 360.1.65 installed at `/usr/bin/lldb`.

I get some warnings during the build phase that could be relevant. When I run cmake, I get this:

```
MACOSX_RPATH is not specified for the following targets:

   bash_execve_redirector
```

When I run make, I get this:

```
ld: warning: directory not found for option '-L/home/ska/local/lib'
```

It looks like this path is hardcoded into `kcov/src/CMakeLists.txt`. I'm not sure what the correct path would be on my machine, I tried `/usr/local/lib` and `/usr/bin`, either of which got rid of the warning but didn't help kcov find LLDB.

Let me know if you need any more info to help debug, or if this sounds like a mistake on my end!

**Comment by SimonKagstrom** [comment]
The /home/ska stuff is something I use locally for some of my custom built libraries. I should probably get rid of that.

What version of OSX do you have? I'm using Sierra and LLDB 360.1.70. Do you have xcode installed?

**Comment by MasonRemaley** [comment]
I'm also running Sierra (10.12.1) and have version 8.1 of the Xcode/the command line tools installed.

**Comment by SimonKagstrom** [comment]
How does the output of otool look? On my system

```
$ otool -L src/kcov 
src/kcov:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/LLDB.framework/LLDB (compatibility version 1.0.0, current version 360.1.70)
```

**Comment by MasonRemaley** [comment]
Here you go:
```
$ otool -L src/kcov 
src/kcov:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/LLDB.framework/LLDB (compatibility version 1.0.0, current version 360.1.65)
```

**Comment by SimonKagstrom** [comment]
OK, looks pretty much like on my system then. I really don't know what's causing this. I haven't got much feedback about the OSX port, except for yours, so I only know that it works on my computer and on the Travis build machines.

**Comment by MasonRemaley** [comment]
Hm okay, I'll see if I can find another MacBook to install it on to figure out if it's an issue with my computer specifically or if it's something to do with the way I set things up.

**Comment by martinseener** [comment]
I've built kcov too using the INSTALL.md guide (installed the prerequisites on 10.12.3) and did the basic install, so cmake, make, make install and when trying to run kcov i get this
>dyld: Library not loaded: @rpath/LLDB.framework/LLDB
    Referenced from: /usr/local/bin/kcov
    Reason: image not found
    Abort trap: 6

otool output is this
>src/kcov:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/LLDB.framework/LLDB (compatibility version 1.0.0, current version 360.1.70)

Any ideas?

**Comment by martinseener** [comment]
Here are the steps from make and make install. I can run "lldb" as well. it opens a lldb shell.

> /usr/local/Cellar/cmake/3.7.2/bin/cmake -H/Users/martinseener/Development/github.com/kcov -B/Users/martinseener/Development/github.com/kcov/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_progress_start /Users/martinseener/Development/github.com/kcov/build/CMakeFiles /Users/martinseener/Development/github.com/kcov/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/bash_execve_redirector.dir/build.make src/CMakeFiles/bash_execve_redirector.dir/depend
cd /Users/martinseener/Development/github.com/kcov/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/martinseener/Development/github.com/kcov /Users/martinseener/Development/github.com/kcov/src /Users/martinseener/Development/github.com/kcov/build /Users/martinseener/Development/github.com/kcov/build/src /Users/martinseener/Development/github.com/kcov/build/src/CMakeFiles/bash_execve_redirector.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/bash_execve_redirector.dir/build.make src/CMakeFiles/bash_execve_redirector.dir/build
make[2]: Nothing to be done for `src/CMakeFiles/bash_execve_redirector.dir/build'.
[  5%] Built target bash_execve_redirector
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/kcov.dir/build.make src/CMakeFiles/kcov.dir/depend
cd /Users/martinseener/Development/github.com/kcov/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/martinseener/Development/github.com/kcov /Users/martinseener/Development/github.com/kcov/src /Users/martinseener/Development/github.com/kcov/build /Users/martinseener/Development/github.com/kcov/build/src /Users/martinseener/Development/github.com/kcov/build/src/CMakeFiles/kcov.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/kcov.dir/build.make src/CMakeFiles/kcov.dir/build
make[2]: Nothing to be done for `src/CMakeFiles/kcov.dir/build'.
[100%] Built target kcov
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_progress_start /Users/martinseener/Development/github.com/kcov/build/CMakeFiles 0

> /usr/local/Cellar/cmake/3.7.2/bin/cmake -H/Users/martinseener/Development/github.com/kcov -B/Users/martinseener/Development/github.com/kcov/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_progress_start /Users/martinseener/Development/github.com/kcov/build/CMakeFiles /Users/martinseener/Development/github.com/kcov/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/bash_execve_redirector.dir/build.make src/CMakeFiles/bash_execve_redirector.dir/depend
cd /Users/martinseener/Development/github.com/kcov/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/martinseener/Development/github.com/kcov /Users/martinseener/Development/github.com/kcov/src /Users/martinseener/Development/github.com/kcov/build /Users/martinseener/Development/github.com/kcov/build/src /Users/martinseener/Development/github.com/kcov/build/src/CMakeFiles/bash_execve_redirector.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/bash_execve_redirector.dir/build.make src/CMakeFiles/bash_execve_redirector.dir/build
make[2]: Nothing to be done for `src/CMakeFiles/bash_execve_redirector.dir/build'.
[  5%] Built target bash_execve_redirector
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/kcov.dir/build.make src/CMakeFiles/kcov.dir/depend
cd /Users/martinseener/Development/github.com/kcov/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/martinseener/Development/github.com/kcov /Users/martinseener/Development/github.com/kcov/src /Users/martinseener/Development/github.com/kcov/build /Users/martinseener/Development/github.com/kcov/build/src /Users/martinseener/Development/github.com/kcov/build/src/CMakeFiles/kcov.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/kcov.dir/build.make src/CMakeFiles/kcov.dir/build
make[2]: Nothing to be done for `src/CMakeFiles/kcov.dir/build'.
[100%] Built target kcov
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_progress_start /Users/martinseener/Development/github.com/kcov/build/CMakeFiles 0
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 preinstall
make[1]: Nothing to be done for `preinstall'.
Install the project...
/usr/local/Cellar/cmake/3.7.2/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /usr/local/bin/kcov
-- Up-to-date: /usr/local/share/man/man1/kcov.1

**Comment by martinseener** [comment]
Hmm, getting this (first line) when running cmake:

> -- Could NOT find LIBBFD (missing:  LIBBFD_BFD_LIBRARY LIBBFD_IBERTY_LIBRARY LIBBFD_OPCODES_LIBRARY LIBBFD_INCLUDE_DIRS)
-- Target architectures: x86_64
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   bash_execve_redirector

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/martinseener/Development/github.com/kcov/build

**Comment by martinseener** [comment]
Okay, i've installed `binutils` using Homebrew and the error message reduced itself from
>Could NOT find LIBBFD (missing:  LIBBFD_BFD_LIBRARY LIBBFD_IBERTY_LIBRARY LIBBFD_OPCODES_LIBRARY LIBBFD_INCLUDE_DIRS)

to
>Could NOT find LIBBFD (missing:  LIBBFD_IBERTY_LIBRARY)

but the error when trying to run kcov remains :(

**Comment by SimonKagstrom** [comment]
Can you try to relink it with verbose as well? I.e.,

```
rm src/kcov
make VERBOSE=1
```

to correlate it with my output above. binutils isn't a strict requirement, and in fact does nothing on OSX anyway.


I'm sorry for not being of much help here, but I'm really fumbling in the dark on this issue.

**Comment by martinseener** [comment]
Made it...

> /usr/local/Cellar/cmake/3.7.2/bin/cmake -H/Users/martinseener/Development/github.com/kcov -B/Users/martinseener/Development/github.com/kcov/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_progress_start /Users/martinseener/Development/github.com/kcov/build/CMakeFiles /Users/martinseener/Development/github.com/kcov/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/bash_execve_redirector.dir/build.make src/CMakeFiles/bash_execve_redirector.dir/depend
cd /Users/martinseener/Development/github.com/kcov/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/martinseener/Development/github.com/kcov /Users/martinseener/Development/github.com/kcov/src /Users/martinseener/Development/github.com/kcov/build /Users/martinseener/Development/github.com/kcov/build/src /Users/martinseener/Development/github.com/kcov/build/src/CMakeFiles/bash_execve_redirector.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/bash_execve_redirector.dir/build.make src/CMakeFiles/bash_execve_redirector.dir/build
make[2]: Nothing to be done for `src/CMakeFiles/bash_execve_redirector.dir/build'.
[  5%] Built target bash_execve_redirector
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/kcov.dir/build.make src/CMakeFiles/kcov.dir/depend
cd /Users/martinseener/Development/github.com/kcov/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/martinseener/Development/github.com/kcov /Users/martinseener/Development/github.com/kcov/src /Users/martinseener/Development/github.com/kcov/build /Users/martinseener/Development/github.com/kcov/build/src /Users/martinseener/Development/github.com/kcov/build/src/CMakeFiles/kcov.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f src/CMakeFiles/kcov.dir/build.make src/CMakeFiles/kcov.dir/build
[  7%] Linking CXX executable kcov
cd /Users/martinseener/Development/github.com/kcov/build/src && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_link_script CMakeFiles/kcov.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -std=c++0x -g -Wall -D_GLIBCXX_USE_NANOSLEEP -DKCOV_LIBRARY_PREFIX=/tmp -DKCOV_HAS_LIBBFD=0 -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/kcov.dir/capabilities.cc.o CMakeFiles/kcov.dir/collector.cc.o CMakeFiles/kcov.dir/configuration.cc.o CMakeFiles/kcov.dir/engine-factory.cc.o CMakeFiles/kcov.dir/engines/bash-engine.cc.o CMakeFiles/kcov.dir/engines/gcov-engine.cc.o CMakeFiles/kcov.dir/engines/python-engine.cc.o CMakeFiles/kcov.dir/filter.cc.o CMakeFiles/kcov.dir/gcov.cc.o CMakeFiles/kcov.dir/main.cc.o CMakeFiles/kcov.dir/merge-file-parser.cc.o CMakeFiles/kcov.dir/output-handler.cc.o CMakeFiles/kcov.dir/parsers/dummy-disassembler.cc.o CMakeFiles/kcov.dir/parser-manager.cc.o CMakeFiles/kcov.dir/reporter.cc.o CMakeFiles/kcov.dir/source-file-cache.cc.o CMakeFiles/kcov.dir/utils.cc.o CMakeFiles/kcov.dir/writers/cobertura-writer.cc.o CMakeFiles/kcov.dir/writers/json-writer.cc.o CMakeFiles/kcov.dir/writers/coveralls-writer.cc.o CMakeFiles/kcov.dir/writers/html-writer.cc.o CMakeFiles/kcov.dir/writers/sonarqube-xml-writer.cc.o CMakeFiles/kcov.dir/writers/writer-base.cc.o CMakeFiles/kcov.dir/dummy-solib-handler.cc.o CMakeFiles/kcov.dir/engines/lldb-engine.cc.o CMakeFiles/kcov.dir/bash-redirector-library.cc.o CMakeFiles/kcov.dir/python-helper.cc.o CMakeFiles/kcov.dir/bash-helper.cc.o CMakeFiles/kcov.dir/html-data-files.cc.o CMakeFiles/kcov.dir/version.c.o  -o kcov -F/Applications/Xcode.app/Contents/SharedFrameworks  -L/home/ska/local/lib -Wl,-rpath,/home/ska/local/lib -Wl,-rpath,/Applications/Xcode.app/Contents/SharedFrameworks  -lstdc++ -lcurl -lm -lz -ldl -framework LLDB
ld: warning: directory not found for option '-L/home/ska/local/lib'
[100%] Built target kcov
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_progress_start /Users/martinseener/Development/github.com/kcov/build/CMakeFiles 0

**Comment by martinseener** [comment]
@SimonKagstrom i see the ld warning:
`ld: warning: directory not found for option '-L/home/ska/local/lib'`

but there is no /home/ska folder here. Is this maybe a hardcoded thing from you?

**Comment by SimonKagstrom** [comment]
The `/home/ska` stuff points to my local library folder in Linux (I don't have it either on my Mac), so that should be harmless (but should probably be removed as well). The difference I see between the two linking commands is that the `-rpath` stuff is after the `-framework` option in my command line, but before in yours. Could you try manually linking with my command line, i.e.,

```
cd src

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -std=c++0x -g -Wall -D_GLIBCXX_USE_NANOSLEEP -DKCOV_LIBRARY_PREFIX=/tmp -DKCOV_HAS_LIBBFD=0 -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/kcov.dir/capabilities.cc.o CMakeFiles/kcov.dir/collector.cc.o CMakeFiles/kcov.dir/configuration.cc.o CMakeFiles/kcov.dir/engine-factory.cc.o CMakeFiles/kcov.dir/engines/bash-engine.cc.o CMakeFiles/kcov.dir/engines/gcov-engine.cc.o CMakeFiles/kcov.dir/engines/python-engine.cc.o CMakeFiles/kcov.dir/filter.cc.o CMakeFiles/kcov.dir/gcov.cc.o CMakeFiles/kcov.dir/main.cc.o CMakeFiles/kcov.dir/merge-file-parser.cc.o CMakeFiles/kcov.dir/output-handler.cc.o CMakeFiles/kcov.dir/parsers/dummy-disassembler.cc.o CMakeFiles/kcov.dir/parser-manager.cc.o CMakeFiles/kcov.dir/reporter.cc.o CMakeFiles/kcov.dir/source-file-cache.cc.o CMakeFiles/kcov.dir/utils.cc.o CMakeFiles/kcov.dir/writers/cobertura-writer.cc.o CMakeFiles/kcov.dir/writers/json-writer.cc.o CMakeFiles/kcov.dir/writers/coveralls-writer.cc.o CMakeFiles/kcov.dir/writers/html-writer.cc.o CMakeFiles/kcov.dir/writers/sonarqube-xml-writer.cc.o CMakeFiles/kcov.dir/writers/writer-base.cc.o CMakeFiles/kcov.dir/dummy-solib-handler.cc.o CMakeFiles/kcov.dir/engines/lldb-engine.cc.o CMakeFiles/kcov.dir/bash-redirector-library.cc.o CMakeFiles/kcov.dir/python-helper.cc.o CMakeFiles/kcov.dir/bash-helper.cc.o CMakeFiles/kcov.dir/html-data-files.cc.o CMakeFiles/kcov.dir/version.c.o  -o kcov -F/Applications/Xcode.app/Contents/SharedFrameworks  -L/home/ska/local/lib  -lstdc++ -lcurl -lm -lz -ldl -framework LLDB -Wl,-rpath,/home/ska/local/lib -Wl,-rpath,/Applications/Xcode.app/Contents/SharedFramework
```

**Comment by martinseener** [comment]
Do i have to remove something before?! Do i have to run make and then link manually? I tried so and got lots of errors:

```clang: error: no such file or directory: 'CMakeFiles/kcov.dir/capabilities.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/collector.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/configuration.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/engine-factory.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/engines/bash-engine.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/engines/gcov-engine.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/engines/python-engine.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/filter.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/gcov.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/main.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/merge-file-parser.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/output-handler.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/parsers/dummy-disassembler.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/parser-manager.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/reporter.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/source-file-cache.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/utils.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/writers/cobertura-writer.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/writers/json-writer.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/writers/coveralls-writer.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/writers/html-writer.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/writers/sonarqube-xml-writer.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/writers/writer-base.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/dummy-solib-handler.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/engines/lldb-engine.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/bash-redirector-library.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/python-helper.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/bash-helper.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/html-data-files.cc.o'
clang: error: no such file or directory: 'CMakeFiles/kcov.dir/version.c.o'
```

**Comment by SimonKagstrom** [comment]
I'm not sure if you should be in the `src/` subdirectory of the build dir or in the build dir itself.

Basically it just has to find `CMakeFiles/kcov.dir/collector.cc.o` etc relative to your PWD, so check where those are located.

**Comment by martinseener** [comment]
They should be in the build dir. The CMakeFiles folder is there but beneath there is no kcov.dir nor the files it searches for :(

**Comment by SimonKagstrom** [comment]
OK, well the other option is to simply retry your linking line and see if moving `-Wl,-rpath,/home/ska/local/lib -Wl,-rpath,/Applications/Xcode.app/Contents/SharedFrameworks` after the `-framework LLDB` option helps.

**Comment by martinseener** [comment]
Do i only have to run make install afterwards and try out?

**Comment by SimonKagstrom** [comment]
No, run the binary directly, i.e.,

```
./kcov

# Or

./src/kcov
```

(Not sure if it ends up in the subdirectory or not, for me it's in `src/`, but cmake might perhaps make local decisions.

**Comment by martinseener** [comment]
Nope...Issue remains :(

**Comment by SimonKagstrom** [comment]
Could you try an xcodebuild and see if that works better? To use that, configure with cmake with

```
cd <build-dir>
cmake -G Xcode <path-to-kcov-src>
xcodebuild
```

**Comment by SimonKagstrom** [comment]
Perhaps something similar to this:

https://kuniganotas.wordpress.com/2011/05/14/how-to-solve-linker-dependencies-on-mac-os-x/

i.e., setting up the library path to look for the LLDB framework dylib. I'm not on a mac machine right now, so I can't lookup the path myself.

**Comment by martinseener** [comment]
I removed all files/folders from my build directory and ran cmake -G Xcode ../ (because build is a subdirectory of kcov) and xcodebuild afterwards. Went fine both but now iam struggeling where i can find the binary now!?!?!?

Output of the above commands is here: https://gist.github.com/martinseener/f9b701d619b59abb7251dd06f19f0f23

**Comment by SimonKagstrom** [comment]
Hehe :-). Looking at the gist output, I think it is in `/Users/martinseener/Development/github.com/kcov/build/src/Debug/kcov`

**Comment by martinseener** [comment]
Wohooo...i think we got a solution for this Issue now!

```
martinseener@Andromeda:~/Development/github.com/kcov/build$ src/Debug/kcov
Usage: kcov [OPTIONS] out-dir in-file [args...]

Where [OPTIONS] are
 -h, --help              this text
 --version               print the version of kcov
 -p, --pid=PID           trace PID instead of executing in-file,
                         in-file is optional on Linux in this case
 -l, --limits=low,high   setup limits for low/high coverage (default 25,75)

 --collect-only          Only collect coverage data (don't produce HTML/
                         Cobertura output)
 --report-only           Produce output from stored databases, don't collect
 --merge                 Merge output from multiple source dirs

 --include-path=path     comma-separated paths to include in the coverage report
 --exclude-path=path     comma-separated paths to exclude from the coverage
                         report
 --include-pattern=pat   comma-separated path patterns to include in the
                         coverage report
 --exclude-pattern=pat   comma-separated path patterns to exclude from the
                         coverage report
 --exclude-line=pat[,...] Consider lines that match the patterns to be non-
                         code lines.
 --exclude-region=start:stop[,...] Exclude regions of code between start:stop
                         markers (e.g., within comments) as non-code lines.

 --coveralls-id=id       Travis CI job ID or secret repo_token for uploads to
                         Coveralls.io
 --strip-path=path       If not set, max common path will be stripped away.
 --uncommon-options      print uncommon options for --help

Examples:
  kcov /tmp/kcov ./frodo                        # Check coverage for ./frodo
  kcov --pid=1000 /tmp/kcov                     # Check coverage for PID 1000
  kcov --include-pattern=/src/frodo/ /tmp/kcov ./frodo # Only include files
                                                       # including /src/frodo
  kcov --collect-only /tmp/kcov ./frodo  # Collect coverage, don't report
  kcov --report-only /tmp/kcov ./frodo   # Report coverage collected above
  kcov --merge /tmp/out /tmp/dir1 /tmp/dir2    # Merge the dir1/dir2 reports
```

**Comment by martinseener** [comment]
Output works. Tried it with a Shell script of mine. Awesome! Can you fix the Mac build instructions to use those above? They seem to work pretty good!

**Comment by SimonKagstrom** [comment]
Great!

I'll update the instructions, but there is still a bug in the cmake script then since the make variant doesn't work everywhere. I'll keep this bug open until it's resolved.

Also, this was a debug build, and I think it would be better to build for Release by default. Something like

```
cd <build-dir>
cmake -G Xcode <path-to-kcov-src>
xcodebuild -configuration Release
```

**Comment by martinseener** [comment]
I tried the `xcodebuild -configuration Release` thing and it worked too. The Binary is now in `src/Release/kcov` and works!

Iam not very familiar with the xcodebuild/make stuff, so you have to probably update/fix them but iam happy to assist you whereever possible!

Is there a way to build the release binary for linux amd64 on macOS as well?

**Comment by SimonKagstrom** [comment]
Great! I'll update the build instructions.

I use [vagrant](https://www.vagrantup.com/) boxes to build and test Linux stuff from the Mac, both 32-bit and 64-bit.

**Comment by zbeekman** [comment]
the CMake folks over on the mailing list, and the venerable @bradking may have some thoughts on how to fix this...

**Comment by springmeyer** [comment]
Here is another workaround if using the normal cmake build:

```
$ install_name_tool -change @rpath/LLDB.framework/LLDB /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/LLDB `which kcov`
```

**Comment by SimonKagstrom** [comment]
@springmeyer thanks!

The strange thing is that for me, normal cmake+make build has always worked without any extra effort. I guess that's good since I'm a OSX newbie :-)

**Comment by palfrey** [comment]
If I do just `xcodebuild -configuration Release`, then `src/Release/kcov` works fine. If I do `xcodebuild -configuration Release -target install` then the copy of kcov in in the install location fails with the dyld issue.

**Comment by SimonKagstrom** [comment]
Is this with the git head or a released version? There has been a major
overhaul of the building system since last release.

**Comment by palfrey** [comment]
This was with v35, but I've just tested against 0167e2bd8cd577d0f1c0ccf869d328a9aad23569 and got the same result.

**Comment by SimonKagstrom** [comment]
Unfortunately, I know much too little about OSX to know how to fix this. @palfrey, in your homebrew formula (thanks by the way!), you add an explicit dependency on xcode. Does that solve this issue, and what does it actually do?

kcov on OSX links against LLDB for Mach-O parsing and setting breakpoints, so in a sense I believe xcode is an actual requirement anyway.

**Comment by palfrey** [comment]
"explicit dependency on xcode" - it works around the issue. So, normally Xcode would only be a compile-time dependency, but because of the `change_install_name` work later in the file (equivalent to the `install_name_tool` command from earlier here), Xcode becomes a runtime dependency. As I noted in comments about the PR "most people needing a code coverage tool are also compiling stuff", so it shouldn't be a big deal, and this method does at least work.

**Comment by SimonKagstrom** [comment]
Ok. So that's basically what @springmeyer does manually above?

Should stuff like that be included in the build system directly to fix this for everyone? Sort of like here: https://stackoverflow.com/questions/13656033/how-do-you-add-an-rpath-to-an-executable-in-cmake-on-build-not-install-on-osx

**Comment by palfrey** [comment]
"So that's basically what @springmeyer does manually above?" - yes, but in a style that the Homebrew developers prefer (although if it was done as part of "make", they'd be fine with that)

Build system > Sounds reasonable to me.

**Comment by SimonKagstrom** [comment]
6391c6f, after some fixup, should fix this issue via the @springmeyer method, so closing this.

**Comment by daemontus** [comment]
In case someone is still running into this issue, make sure you have CommandLineTools installed correctly (for example http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/). Having Xcode installed does not seem to automatically install command line tools in a way that kcov can use.
