### ISSUE TITLE
Feature Request: Add json writer/report

### ISSUE THREAD

**Issue by brycefisher** [SimonKagstrom/kcov#167]
## Goal

I'm trying to get access to the overall coverage percentage for a personal rust-lang project so that I can integrate with [GitlabCI's test coverage parser](https://docs.gitlab.com/ce/user/project/pipelines/settings.html#test-coverage-parsing). This parser is very naive, and can only parse regex written to STDOUT during a test run.

## Propoal

IMHO, the most flexible and straightforward way of achieving this goal would be to change the formatting of the HTML report to expose the json data as a parse-able json file.

## Alternatives

 * Extend GitlabCI with Cobertura support - this change would require more engineering effort for a strictly narrower class of features. It would require a new API endpoint to receive the Cobertura reports, and then either write custom (aka brittle) support for parsing the XML _or_ embedding the Cobertura jar inside Gitlab which is a Ruby on Rails application. This endpoint would do arithmetic on the parsed Cobertura to determine overall coverage, and discard all detailed coverage statistics. The end result would be that only one CI provider is extended to cover one additional coverage report format. The upshot of this approach is that GitlabCI would now integrate with any project that produces a Cobertura report for test coverage.
 * Use the Cobertura jar to calculate project test coverage - this work would need to be repeated for any project which wished integrate kcov and GitlabCI, thus having an even lower leverage. Additionally, it would add the requirement to the CI environment that it must support the JVM. The upshot here is that no new code needs to be added to Cobertura, kcov, nor GitlabCI.

## Rationale

 1. _Leverage_: many tools can parse json (including the cli tool [`jq`](https://github.com/stedolan/jq)), so explicitly integrating with other tools might not be necessary
 2. _Trivial_: Conceptually, the changes to the output are trivial
 3. _Straightforward_: a cursory inspection of the json generation code makes the level of effort seem low.

## How it is now

Each [`.json` file](http://simonkagstrom.github.io/kcov/kcov-example-output/kcov-merged/index.json) currently has a structure similar to this (this is the global index):

```js
var percent_low = <INT>; var percent_high = <INT>;
var header = { 'command' : 'ut', 'date' : <ISODATE>, 'instrumented' : <TOTAL LINE COUNT>, 'covered' : <COVERED LINE COUNT>,};
var data = [
{'link':<RELATIVE URL>, 'title':<LINK TEXT>, 'summary_name':<ABSOLUTE PATH>, 'covered_class':<IDENTIFIER>,'covered':<PERCENTAGE COVERED>, 'covered_lines':<COVERED LINE COUNT>,'uncovered_lines':<UNCOVERED LINE COUNT>,'total_lines' : <TOTAL LINE COUNT>},
];
var merged_data = [];
```

## Changes

In each json file (whitespace for readerability, probably more similar to existing whitespace):

```json
{
  "percent_low": <INT>,
  "percent_high": <INT>,
  "header": {
    "command": "ut",
    "date": <ISODATE STRING>,
    "instrumented": <TOTAL LINE COUNT>,
    "covered": <COVERED LINE COUNT>
  },
  "data": [
    {
      "link":<RELATIVE URL>,
      "title": <LINK TEXT>,
      "summary_name":<ABSOLUTE PATH>,
      "covered_class": <IDENTIFIER>,
      "covered": <PERCENTAGE COVERED>,
      "covered_lines":<COVERED LINE COUNT>,
      "uncovered_lines": <UNCOVERED LINE COUNT>,
      "total_lines": <TOTAL LINE COUNT>
    },
  ],
  merged_data: []
}
```

In [`data/js/kcov.js`](http://simonkagstrom.github.io/kcov/kcov-example-output/kcov-merged/data/js/kcov.js), create a function (such as `init()`) that takes the path to a json file. After it loads the json file using `$.getJSON()`, it puts the json data into scope and sets up the `window.onload` callback much as before.

In each html report, we would omit the script tag for the json file, and instead invoke the `init()` function with the path to the json data.

## Open Questions

 * Does this approach sound acceptable? Might a PR be accepted which follows this approach?
 * ~~Does the [`merged_data`](https://github.com/SimonKagstrom/kcov/blob/master/src/writers/html-writer.cc#L203) ever get parsed and updated elsewhere in kcov?~~

**Comment by brycefisher** [comment]
I've never written C++ before, so hopefully my forthcoming PR isn't too horrifying too read :-)

**Comment by brycefisher** [comment]
@SimonKagstrom I was mulling this over a bit more and I have a slightly different approach to suggest. My new proposal would be to simply create one new and separate json report per project (much like how the Cobertura and SonarQube writers work currently).

Here's my reasoning:
- Chrome probably won't allow a `$.getJSON()` for a `file://` protocol url for security reasons, viewing a report locally would stop working :-(
 - Conceptually, those data files are tightly coupled to the HTML report themselves. It would probably be more convenient to have a larger consolidated JSON file with its own independent structure for use by other tools (like GitlabCI).

By separating out a new JSON writer, the ancillary benefits are that nothing about the existing HTML reports needs to be refactored and this can be a purely additive change.

In terms of the content of the file, I think I would still output a file very similar to my original proposal, but as a single file. Here's a simple example:

```json
{
  "percent_low": 25,
  "percent_high": 75,
  "command": "ut",
  "date": <ISODATE STRING>,
  "covered_lines": 999999,
  "total_lines": 1000000,
  "paths": [
    {
      "file": "file.cc",
      "path": "/app/src/file.cc",
      "covered_class": "main",
      "percent_covered": "99.9",
      "covered_lines": 999999,
      "uncovered_lines": 1,
      "total_lines": 1000000
    }
  ]
}
```

Thoughts?

**Comment by SimonKagstrom** [comment]
OK! Yes, local reports are good to have - after all they account for probably 90% of my own use.

And I agree, a new "writer" should be the best way to implement this. As you note, it should be pretty straight forward to use the Cobertura writer as a template. The only tricky part is that it needs to be registered twice in main.cc, for merged and norma modes (yep, that part is pretty ugly). Naming it json-writer.cc should be good I guess?

Let me know if you run into issues!


One thing I actually wonder about is how to document all this. I'm a bit old-fashioned, so there's a man-page, but I don't always remember to update it. And besides, modern people probably just look at e.g., github instead anyway, so README.md also contains some usage info. However, it's not complete, and that file also starts to become large. Perhaps it's better to link from README.md to specific usage examples, e.g., SonarQube, Travis/Coveralls, Travis/Codecov, Gitlab etc?

**Comment by brycefisher** [comment]
Good catch! I'll make sure to add docs to the man page and perhaps a FORMATS.md doc linked from the README?

**Comment by SimonKagstrom** [comment]
Something like that should do it! However, I think a link is good enough in the man page. The man page is probably best to leave pretty short, focusing on the command line options.

**Comment by SimonKagstrom** [comment]
Implemented, so closed!

**Comment by SimonKagstrom** [comment]
@brycefisher: Is there a place where I can see an example of this in action by the way?

**Comment by brycefisher** [comment]
@SimonKagstrom yes! I'm working on a pet project and I was keeping it closed source until it...um, does something interesting. I'd hate to be accused of creating vaporware :-)

I'm planning to write a blog post this week about how to integrate kcov with rust on gitlab-ci later this week. 

In the meantime, I may as well make my gitlab repo public at least as a demonstration of the json report feature. I'll update this issue with the url once I do!

**Comment by brycefisher** [comment]
@SimonKagstrom -- my personal project (still very near the beginning of development) is here:
https://gitlab.com/bff/rn

You can see the code coverage badge being output to the README:
![kcov-json-report-in-gitlab](https://cloud.githubusercontent.com/assets/220106/21879274/557ddf0e-d84c-11e6-890e-07500995112d.png)

I've configured my CI/CD pipelines (aka GitlabCI) to parse test coverage using this regex:

![^Percent coverage: "(\d+\.\d+)"%$](https://cloud.githubusercontent.com/assets/220106/21879307/a4201cee-d84c-11e6-8d65-76c5c60c7eb7.png)

You can see my `.gitlab-ci.yaml` configuration which compiles my rust test binary _with_ dead code (otherwise coverage is always falsely to be :100:), runs it through kcov using the `--verify` flag, and parsing the `coverage.json` using jq.

```yaml
unit_test:
   stage: test
   script:
     - "RUSTFLAGS='-C link-dead-code' cargo test --no-run"
     - "kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/rn-*"
     - "echo \"Percent coverage: $(jq .percent_covered target/cov/rn-*/coverage.json)%\""
```

https://gitlab.com/bff/rn/blob/master/.gitlab-ci.yml#L20

That's pretty much all there is to it :smile:
