### ISSUE TITLE
version v33 not tagged

### ISSUE THREAD

**Issue by Ragnaroek** [SimonKagstrom/kcov#174]
This would make building the latest docker image easier:
https://github.com/Ragnaroek/kcov_docker

**Comment by SimonKagstrom** [comment]
Version 33 isn't really released yet, but perhaps it's time to do it. I'll fixup the ChangeLog and release it today or tomorrow!

Thanks for the kcov docker! There was recently some discussion in Issue #115 about a docker image built continuously from the git HEAD by the way.

**Comment by SimonKagstrom** [comment]
I've tagged v33 now, so closing!
