### ISSUE TITLE
traced application crashes due to to int3 instructions in bad place

### ISSUE THREAD

**Issue by oliver** [SimonKagstrom/kcov#18]
This might well be a bug in my application or in the compiler, but it might be useful to document this issue here anyway: when running a somewhat complicated application under kcov, the application crashes with Segmentation Fault (it doesn't crash when run without kcov, and it's also pretty much Valgrind-clean).

The crash happens for example in `std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_fill_insert()` called from `std::vector::resize()`.

Here's what gdb shows in `disassemble /r` (look at 0x080d1658):
```
   0x080d164d <+349>:    8b 45 08       mov    0x8(%ebp),%eax
   0x080d1650 <+352>:    8b 4d dc       mov    -0x24(%ebp),%ecx
   0x080d1653 <+355>:    8b 5d 08       mov    0x8(%ebp),%ebx
   0x080d1656 <+358>:    89 10  mov    %edx,(%eax)
   0x080d1658 <+360>:    89 cc  mov    %ecx,%esp
   0x080d165a <+362>:    04 cc  add    $0xcc,%al
   0x080d165c <+364>:    d0 8b cc d4 01 d0      rorb   -0x2ffe2b34(%ebx)
   0x080d1662 <+370>:    89 43 08       mov    %eax,0x8(%ebx)
   0x080d1665 <+373>:    83 c4 4c       add    $0x4c,%esp
   0x080d1668 <+376>:    5b     pop    %ebx
   0x080d1669 <+377>:    5e     pop    %esi
```

Here's what `objdump -d` shows for the same place:
```
 80d164d:       8b 45 08                mov    0x8(%ebp),%eax
 80d1650:       8b 4d dc                mov    -0x24(%ebp),%ecx
 80d1653:       8b 5d 08                mov    0x8(%ebp),%ebx
 80d1656:       89 10                   mov    %edx,(%eax)
 80d1658:       89 48 04                mov    %ecx,0x4(%eax)
 80d165b:       89 d0                   mov    %edx,%eax
 80d165d:       8b 55 d4                mov    -0x2c(%ebp),%edx
 80d1660:       01 d0                   add    %edx,%eax
 80d1662:       89 43 08                mov    %eax,0x8(%ebx)
 80d1665:       83 c4 4c                add    $0x4c,%esp
 80d1668:       5b                      pop    %ebx
 80d1669:       5e                      pop    %esi
```

IIUC there's an `int3` instruction at 0x080d1659, in the middle of another instruction?

I think I'd seen a similar issue with bcov as well one time, and traced it back to weird debug info (which pointed into the middle of an x86 instruction). Not sure if that's the same problem again, because this time I have a newer compiler and platform.

This happens with latest kcov, with an application compiled with g++ 4.4.7-3 under RHEL6.4 x86-64.

**Comment by SimonKagstrom** [comment]
Fixed with 007b94e. There are some fixups to be made (mainly for the build), but you can now run with

```
kcov --verify /tmp/kcov <program>
```

and kcov will verify that all breakpoints are setup on instruction boundaries. Interestingly, even with 4.9.2 I get a few hits with verify for kcov itself (having to do with C++ exception handling).
