### ISSUE TITLE
argument given to python in double quotes not working

### ISSUE THREAD

**Issue by bhaskarrana** [SimonKagstrom/kcov#183]
Hi Simon,
Below is the test script which will demonstrate that argument given in double quotes not working as expected, though it works when used in python shell
cat test.py

import sys
if len(sys.argv) == 4 :
  print "if cond"
else :
  print "else cond"

When ran python command 
$python test.py "1 2 3 4" a b
if cond    ( output)
when ran with kcov comand 
 $kcov /tmp/out  test.py '1 2 3 4' a b
Or
$kcov /tmp/out test.py "1 2 3 4" a b

else cond  ( output)
To fix this issue
$kcov /tmp/out  test.py "'1 2 3 4'" a b
if cond    ( output)

So we have to put single quote "'"  inside the double quotes.
Is it a bug or it works like this.

Regards
Bhaskar Rana

**Comment by SimonKagstrom** [comment]
That's a bug, I'll look into fixing it!

**Comment by bhaskarrana** [comment]
Hi Simon,

I made changes in the following line of the following file **python-engine.cc**

                                s += "'"+ std::string(argv[i]) + "'"+ " ";

as earlier it was
       s += std::string(argv[i]) + " ";

After making this changes and it works as expected.
Kindly advice is it the correct way .

Regards
Bhaskar Rana

**Comment by SimonKagstrom** [comment]
Yes, sounds like the correct way. Care to fork kcov and send a pull request?

**Comment by SimonKagstrom** [comment]
Fixed with be91345 (committed with you as author)!

**Comment by bhaskarrana** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hi Simon Apologies for delayed response, as busy withSome personal stuff. Thanks for the fix, as I was getting some permission issue on git
Regards Bhaskar Rana 


Sent from Yahoo Mail for iPhone


On Saturday, February 18, 2017, 3:32 AM, Simon Kagstrom <notifications@github.com> wrote:


Closed #183.
