### ISSUE TITLE
code style: K&R -> Allman

### ISSUE THREAD

**Issue by SimonKagstrom** [SimonKagstrom/kcov#190]
I now prefer braces on the next line :-)

**Comment by edge226** [comment]
What led to this occurance? :-)

**Comment by SimonKagstrom** [comment]
Well, we use Allman style at work, so I tend to write in that style by default. I've also used it in a few places in kcov by mistake, so I think it's time to switch sometime soonish.

Also, I've got a better monitor now with higher vertical resolution, so there's no need to save space :-)

**Comment by edge226** [comment]
I personally find it easier to track opening/closing braces at a glance with Allman style. I originally switched because someone said they saw unhappy faces in my code and said that looking at my code made them unhappy because of it.

Certainly an odd occurance.

**Comment by SimonKagstrom** [comment]
Fixed with 495c1d0.
