### ISSUE TITLE
rust code coverage

### ISSUE THREAD

**Issue by serayuzgur** [SimonKagstrom/kcov#200]
Hi ,
First of all, thanks for such a nice project. I was trying to upload code coverage to codecov.io from travis-ci. I did what is necessary from looking [Codecov example](https://github.com/codecov/example-rust) but I got a strange error. 
`kcov: error: Can't find or open target/debug/weld-3c361d2e9fd87aff.d` 
You can see all the build log from [Here](https://travis-ci.org/serayuzgur/weld/jobs/226819078)

Do you have any idea what could be the problem?

**Comment by SimonKagstrom** [comment]
Thanks :-)

kcov does seem to run the binary, i.e., the lines

```
kcov: 106 invalid breakpoints skipped in target/debug/weld-3c361d2e9fd87aff
running 2 tests
test service::utils::tests::split_path_test ... ok
test service::query::tests::split_query_test ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured
```

in the output. The error message is probably due to someone passing a non-executable to kcov, from the filename, it looks like a directory to me? Further up, this loop and command looks strange:

```
for file in target/debug/weld-*; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done
```

**Comment by SimonKagstrom** [comment]
Thanks!

Well, kcov does seem to run the binary


```
for file in target/debug/weld-*; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done
```

**Comment by serayuzgur** [comment]
Hi,
You were totally right. It was about the file loop. kcov has nothing to do with it but you solved it anyway. It is nice to have polite people like you around. 
Thanks.
