### ISSUE TITLE
bfdconfig.camke

### ISSUE THREAD

**Issue by mcgrady1** [SimonKagstrom/kcov#201]
Hi,
   cmake problem:
   1)could not find a package configuration file provided by "Bfd" with any of the follow names
   2)include could not find load file: TargetArch

   i have install all dependency lib,binutils version == 2.24
   although add the cmake_prefix_path, it didn't work

**Comment by SimonKagstrom** [comment]
Hi!

What is the cmake command line and can you paste the cmake output. I typically run something like

```
git clone <kcov>
cd kcov
mkdir bld
cd bld
cmake ..
```

**Comment by mcgrady1** [comment]
Hi,

    i have solve the problem, i mkdir build in kcov/src/

    thanks for your reply

**Comment by SimonKagstrom** [comment]
OK, good!
