### ISSUE TITLE
Does kcov need special permissions to run in a Jenkins job on OSX?

### ISSUE THREAD

**Issue by chrisdjauntvr** [SimonKagstrom/kcov#205]
I expect others are regularly making use of Jenkins with kcov, and Github doesn't seem to have a forum section, so this'll have to do...

I'm trying to run kcov through jenkins on a macbook pro, but I keep running into what I think are permissions issues that I can't seem to resolve.

I keep getting this:

```
> ./tools/kcov ./kcov-output <my executable>
kcov: error: Launch failure
kcov: error: Can't start/attach to <my executable>
```

Running the exact same command locally on the given machine worked, except it prompted for XCode Dev Tools access. After handling the pop-up, it works absolutely fine.

I then gave the Jenkins user permanent XCode Dev Tools access and added a statement to verify its enabled during execution, but I still get the same error:

```
> DevToolsSecurity -enable
Developer mode is already enabled.
> ./tools/kcov ./kcov-output <my executable>
kcov: error: Launch failure
kcov: error: Can't start/attach to <my executable>
``` 

Is there something else kcov needs (under OSX or not) in order to run within the Jenkins daemon context?

Again, running the command locally on the desktop works absolutely fine so it's something funky with the world of Jenkins itself.

**Comment by SimonKagstrom** [comment]
This means that the LLDB library can't launch the process. I'm not very familiar with OSX, but I guess there might be restrictions on e.g., ptrace (which LLDB and kcov uses). You could perhaps try to start lldb from jenkins and see how that goes?

Perhaps a setting for Jenkins?

I've been using kcov from Jenkins, but that was on Linux.

**Comment by chrisdjauntvr** [comment]
Yeah, running lldb from the Jenkins script seemed to work:
```
[Test-Sandbox] Running shell script
+ lldb <my executable>
(lldb) target create "<my executable>"
Current executable set to '<my executable>' (x86_64).
```
But then immediately spit out the same error as before on the kcov command. Unfortunately I don't have a linux box on-hand to try it there and its proprietary code so I can't hand it over for someone else to test :(

**Comment by SimonKagstrom** [comment]
Does lldb work if you do "run" as well? That's the part that fails with kcov, target create works.

**Comment by SimonKagstrom** [comment]
Actually, you could try to see what happens if you just remove the check for Fail() in the error object in engines/lldb-engine.cc around line 191:

```
		if (error.Fail()) {
			error("Launch failure\n");

			return false;
		}
```

the process was created OK (otherwise it would have printed another message), so I'm not sure why it would fail otherwise.

**Comment by chrisdjauntvr** [comment]
Yep, looks like it can launch it, but not attach:

```
[SDK-Test-Sandbox] Running shell script
+ lldb -o run <my executable>
(lldb) target create "<my executable>"
Current executable set to '<my executable>' (x86_64).
(lldb) run
error: process exited with status -1 (unable to attach)
```

Also tried commenting out the above, recompiling, shoving it through Jenkins, but Jenkins just tells me it `caught error` without telling me what that error was ...

But, funnily enough, I dug out an old Mac-Mini, put Jenkins on it, ran the same command and it magically worked! So, Jenkins doesn't have a problem with attaching debuggers to processes, just THAT machine running Jenkins. Not sure what plugin or global setting might be causing that, but at least I've got my workaround.

**Comment by SimonKagstrom** [comment]
Great! Then it's some configuration issue, perhaps ptrace can be disabled? In Linux, there are ways to restrict ptrace, but that mainly affects ptracing non-child processes.

I'm closing this issue, but if you find out what caused the problem, feel free to update with a comment about how to solve this!
