### ISSUE TITLE
Coverage data not merged on same-named bash scripts

### ISSUE THREAD

**Issue by astraw38** [SimonKagstrom/kcov#208]
Seen by [this example](https://gist.github.com/astraw38/9c9e62f4af218ddf762ba2a6d6a11fc8). 

If you run kcov on two identically named bash scripts (but in different folders), you will only get results from the *last* script. If you then run it on a different bash script, you'll get results for all 3 of the script executions.

**Comment by astraw38** [comment]
I believe [this](https://github.com/SimonKagstrom/kcov/blob/master/src/main.cc#L125) line is to 'blame' for the bug. Since it only checks the filename, not the full file path, this would return 0 for the metadata count, even though there technically could be X metadata files for a given filename (over multiple runs)


I'm not completely sure that line is necessary either, since the metadata is counted on start, and the contents of the metadata folder would be empty until the ``onStop()`` function is called. 

@SimonKagstrom thoughts? I don't know that much about the internals, so I might be missing something.

**Comment by SimonKagstrom** [comment]
Thanks for the analysis! I'll take a look at this in a while, but I'll be offline for some time now (well, at least not by the computer).

Anyway, thanks for the detailed and very good bug reports!

**Comment by SimonKagstrom** [comment]
Yes, I agree with your conclusions (now having looked at it!).

I think the solution is to incorporate some more logic into the metadata naming, e.g., hashing the full path of the file as well to fix these situations.

I actually don't think it's only for bash scripts either, binaries with the same name should give the same results.

**Comment by SimonKagstrom** [comment]
Sorry for this taking so long. I'll admit I simply forgot about this bug report.

Anyway, with f4bf893 it should now be fixed - at the very least your example works fine for me now.

Thanks for the detailed analysis!
