### ISSUE TITLE
Installation instructions for OS X are out of date

### ISSUE THREAD

**Issue by jdanford** [SimonKagstrom/kcov#209]
The installation instructions for OS X say to install the Homebrew formula `homebrew/dupes/zlib`, but `homebrew/dupes` was deprecated [in April](https://github.com/Homebrew/homebrew-dupes/commit/cc106b305e6590e6d1f48be9623f2df4f4d2d187), so the install command should be changed to use the normal `zlib` formula.

**Comment by SimonKagstrom** [comment]
I've been on computer-less travelling for a while, so sorry for the late response.

Thanks for the heads-up, I'll fix this (although probably not until tomorrow or so!)

**Comment by SimonKagstrom** [comment]
Fixed with 1324791, thanks!
