### ISSUE TITLE
Doesn't seem to generate coverage report for shared libraries

### ISSUE THREAD

**Issue by kannaiah** [SimonKagstrom/kcov#218]
I tried kcov for the first time and the tool is pretty nice.
I have a shared library that is built to have debug symbols (I'm sure of it because I could source debug using gdb)
But the kcov is not doing coverage for shared library.

**Comment by SimonKagstrom** [comment]
Linux or OSX? Shared library instrumentation is only supported under Linux. Another limitation is that it must match the host architecture, ie., a i386 library can't be instrumented on x86_64 (issue #131).

Is your binary also built with debug symbols? Probably needed even if you're only interested in the library. You can try passing ```--debug=15``` to see if it at least tries to parse the library (warning: lots of output!).

**Comment by kannaiah** [comment]
My machine is x86_64 and my binary I'm using is 32bit, is it same issue as #131 ?
This is on Linux, the library does have debug symbols.

**Comment by SimonKagstrom** [comment]
Yep, that's #131. It shouldn't be too difficult to fix though. Kcov uses a
LD_PRELOADed library for detecting shared libraries, and this would have to
be built in two versions for 64-bit systems and then dynamically selected
in runtime.

Alternatively, /proc can possibly be used as well.

**Comment by SimonKagstrom** [comment]
Closing as a duplicate to #131.
