### ISSUE TITLE
How to exclude some processes by name from coverage?

### ISSUE THREAD

**Issue by kannaiah** [SimonKagstrom/kcov#220]
I have many levels of scripting on top actual test binary.
And a test binary is executed with different options by the scripts

If I can only include test process by name then I do not have to change any existing scripting for generating coverage. Otherwise I would have to handle merging of coverage reports my self.

I used `--include-path` but this is causing slowdown.

Thank you.

**Comment by SimonKagstrom** [comment]
Hmm.. So your scripts run kcov on some binary which you don't want to collect coverage for?

So the name exclusion would be to simply ignore some runs? Or do I misunderstand you?

**Comment by kannaiah** [comment]
Sorry, I wasn't clear.
I was running my scripts through kcov.
I just read another ticket #177 so it might not be possible to get coverage of my tests as my top level scripts are in bash and python.

**Comment by SimonKagstrom** [comment]
Aha, yes, I'm afraid that isn't possible at the moment. I'm not quite sure how to implement it either, so for now I'm not investigating it further. The difficult thing is to determine what are actual Python scripts from bash (and the other way around!).

Closing as a duplicate to #177, reopen if this isn't the case.
