### ISSUE TITLE
bash: Show uncovered files in report

### ISSUE THREAD

**Issue by Fatlog** [SimonKagstrom/kcov#224]
Hi,

I'm using kcov to report code coverage on a project that is mainly made up of bash scripts.
We are building out the unit test suite retrospectively.
Is it possible to include uncovered scripts in the html report?

Ideally I would like to be able to see what scripts have not yet been covered by tests and also identify any new scripts that may get added without an accompanying unit test.

**Comment by SimonKagstrom** [comment]
Unfortunately, it's very difficult to actually know what scripts will be
sourced by a bash script, so it's not currently possible.

 One way of doing something like it would be to add an option to scan a
directory for files and add them to the list of executable files. I'm not
sure if that would fit your particular case though?

I.e., something like

```
kcov --add-source-files=dir [...] your-program
```

**Comment by Fatlog** [comment]
Hi Simon,

Thanks for the feedback. Something like your suggestion would be ideal if it were possible.
The issue I have right now is the covered % to me doesn't tell the whole story. 
It could say 90% but my tests actually only cover 10% of the codebase.

I previously looked at another option for bash coverage...

https://github.com/infertux/bashcov

This does actually instrument all of the bash scripts in the project folder. 
However it doesn't provide as many configuration options as kcov and introduces a dependency on Ruby. Also, in my specific test scenario it tends to overwrite data as it progresses making it inaccurate.

Hence I started using kcov which works very well but it would be handy if it were able to show gaps in my test suite.

Thanks

**Comment by SimonKagstrom** [comment]
Fixed with 0dd22bd . Kcov now by default parses the directory of the script to find other scripts. This behavior can be turned off via an option, and another option allows passing directories manually as we discussed above.

So I think your test case should work by default now.

**Comment by Fatlog** [comment]
Great. Thanks!

**Comment by tooptoop4** [comment]
@SimonKagstrom has this option been removed?

**Comment by SimonKagstrom** [comment]
No, should still be there. Has it been broken?

**Comment by tooptoop4** [comment]
unfortunately

**Comment by SimonKagstrom** [comment]
I just tested it here, and it works for me.  I.e., with a

```
/tmp/kalle/shell-main
/tmp/kalle/manne/short-test.sh
```

where `shell-main` does not invoke `short-test.sh`, I see both in the report (with `short-test.sh` uncovered) when running

```
kcov /tmp/kcov /tmp/kalle/shell-main
```

what are the circumstances when it doesn't work?

**Comment by tooptoop4** [comment]
adding ```--bash-parse-files-in-dir=/myshfolder``` solved this
