### ISSUE TITLE
Empty lines in output when testing bash

### ISSUE THREAD

**Issue by ErikasRaginis** [SimonKagstrom/kcov#225]
![empty-lines](https://user-images.githubusercontent.com/30409860/32484298-fb1adc22-c3a7-11e7-881c-2c480d6b0326.jpg)

**Comment by SimonKagstrom** [comment]
What browser is this? I don't see these empty lines with my tests with google chrome.

Can you run a test on <kcov-source-dir>/tests/bash/shell-main? I tried that one, and it looks OK here. Do you have any special line-endings in your file?

**Comment by ErikasRaginis** [comment]
I used mozilla firefox, but also tested in on chromium. I'm using ubuntu.
I use normal line endings.
I think i found the issue, i was using kcov installed from apt, while the version from git seems to work.
May i suggest a -v, --version option?

**Comment by SimonKagstrom** [comment]
OK, thanks!

There is a --version option since a few versions back:

```
$ src/kcov --version
kcov v34-15-g1d3e
``

I think the Ubuntu packaged version is very, very old, so that will not work very well (also for other reasons). Closing since this is for an older release! It might be possible to submit a bug to Ubuntu though.
