### ISSUE TITLE
kcov error: cannot open but works with strace

### ISSUE THREAD

**Issue by particleflux** [SimonKagstrom/kcov#226]
I'm trying to setup kcov as a coverage reporter for bats on Circle-CI, but regardless of which command I execute under kcov, it says: 

```
Error: Cannot open <command>
```

Interesting thing though, if I run the whole thing under _strace_, everything works as expected!

`kcov coverage/ bats tests/` [output](https://gist.github.com/particleflux/4cef120c43fb0acd66c57c95b3977b52)  vs `strace kcov coverage/ bats tests/` [output - warning, big file with 8k lines](https://gist.github.com/particleflux/fc1ce0cdf3b49f9b46e7493758eeb69d)

* kcov version: self compiled from current master (the one of ubuntu repositories fails with the same error)
* OS: Ubuntu 14.04.4 LTS 
* Kernel: Linux box526 3.13.0-129-generic #178-Ubuntu SMP Fri Aug 11 12:48:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

(this is a default circle ci 1.0 environment)

**Comment by particleflux** [comment]
Arg, nevermind, somehow the self compiled kcov wasn't picked up by bash, but was picked by strace. Different executables. Works when I use the latest master and execute the self compiled binary directly.

**Comment by SimonKagstrom** [comment]
OK, great!

Yes, the ubuntu one is old and doesn't work very well.

**Comment by SimonKagstrom** [comment]
And the reason is that the old Ubuntu version requires the full path to the program to test, while the newer kcov also checks in PATH.

**Comment by particleflux** [comment]
Ah, that explains, thanks!
