### ISSUE TITLE
Can't find BFD or binutils when building on OS X

### ISSUE THREAD

**Issue by NamsooCho** [SimonKagstrom/kcov#231]
I'm using kcov via cargo-travis.
When building kcov, the message "BFD or binutils not found" is shown.
Build is well done.
But, after first build and use, reuse of kcov "./kcov --verify ..." doesn't working.
I installed bintutils " brew install binutils".

**Comment by SimonKagstrom** [comment]
The "BFD or binutils" missing message is OK - binutils is not used or needed on OSX (and not a strict requirement on Linux either).

In what way is it not working? If you build an hello-world program and compile with `-g` (for debug information), does running

```
   kcov /tmp/kcov <your-program>
```

produce browsable results in  /tmp/kcov/index.html?

**Comment by NamsooCho** [comment]
OK.
Maybe, it's problem of cargo-travis.

**Comment by SimonKagstrom** [comment]
Well, I use it with travis-ci myself, e.g., https://travis-ci.org/SimonKagstrom/kcov/jobs/326821565

and it works on OSX as well, so I think it should be OK in that environment.
