### ISSUE TITLE
Bug in SHELL script (echo)

### ISSUE THREAD

**Issue by kamontat** [SimonKagstrom/kcov#233]
Compiler didn't known if your echo have multiple lines
- 100%
```bash
echo "Hello world"
```
- 33%
```bash
echo "
Hello world
"
```

![screen shot 2018-01-25 at 06 58 13](https://user-images.githubusercontent.com/14089557/35363561-2669ad4e-019d-11e8-84d9-07c3f9334541.png)

**Comment by SimonKagstrom** [comment]
Thanks for the report! This is one of the bugs which are really only solvable when #145 is fixed, so I'm closing this for now.
