### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by huangshiyou** [SimonKagstrom/kcov#235]
When generating Makefile by 'cmake ..', it reports

 error: CPU you selected does not support x86-64 instruction set

Any ideas?

**Comment by SimonKagstrom** [comment]
What CPU is this on? Can you post the complete output from cmake?

**Comment by huangshiyou** [comment]
CPU info:
odel name	: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 
Error Info:

'''
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: 

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -c

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -Aa

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
cc: fatal error: no input files
compilation terminated.
Determining if the C compiler works failed with the following output:
Change Dir: /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_7e90e/fast"
/usr/bin/make -f CMakeFiles/cmTC_7e90e.dir/build.make CMakeFiles/cmTC_7e90e.dir/build
make[1]: Entering directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_7e90e.dir/testCCompiler.c.o
/usr/bin/cc    -O3 -march=i686    -o CMakeFiles/cmTC_7e90e.dir/testCCompiler.c.o   -c /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
CMakeFiles/cmTC_7e90e.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_7e90e.dir/testCCompiler.c.o' failed
make[1]: *** [CMakeFiles/cmTC_7e90e.dir/testCCompiler.c.o] Error 1
make[1]: Leaving directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_7e90e/fast' failed
make: *** [cmTC_7e90e/fast] Error 2


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: 

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -c

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -Aa

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
cc: fatal error: no input files
compilation terminated.
Determining if the C compiler works failed with the following output:
Change Dir: /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_79357/fast"
/usr/bin/make -f CMakeFiles/cmTC_79357.dir/build.make CMakeFiles/cmTC_79357.dir/build
make[1]: Entering directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_79357.dir/testCCompiler.c.o
/usr/bin/cc    -O3 -march=i686    -o CMakeFiles/cmTC_79357.dir/testCCompiler.c.o   -c /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
CMakeFiles/cmTC_79357.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_79357.dir/testCCompiler.c.o' failed
make[1]: *** [CMakeFiles/cmTC_79357.dir/testCCompiler.c.o] Error 1
make[1]: Leaving directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_79357/fast' failed
make: *** [cmTC_79357/fast] Error 2


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: 

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -c

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -Aa

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
cc: fatal error: no input files
compilation terminated.
Determining if the C compiler works failed with the following output:
Change Dir: /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_cfef7/fast"
/usr/bin/make -f CMakeFiles/cmTC_cfef7.dir/build.make CMakeFiles/cmTC_cfef7.dir/build
make[1]: Entering directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_cfef7.dir/testCCompiler.c.o
/usr/bin/cc    -O3 -march=i686    -o CMakeFiles/cmTC_cfef7.dir/testCCompiler.c.o   -c /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
CMakeFiles/cmTC_cfef7.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_cfef7.dir/testCCompiler.c.o' failed
make[1]: *** [CMakeFiles/cmTC_cfef7.dir/testCCompiler.c.o] Error 1
make[1]: Leaving directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_cfef7/fast' failed
make: *** [cmTC_cfef7/fast] Error 2


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: 

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -c

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc 
Build flags: -O3;-march=i686
Id flags: -Aa

The output was:
1
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
CMakeCCompilerId.c:1:0: error: CPU you selected does not support x86-64 instruction set


Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
cc: fatal error: no input files
compilation terminated.
Determining if the C compiler works failed with the following output:
Change Dir: /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_41dd1/fast"
/usr/bin/make -f CMakeFiles/cmTC_41dd1.dir/build.make CMakeFiles/cmTC_41dd1.dir/build
make[1]: Entering directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_41dd1.dir/testCCompiler.c.o
/usr/bin/cc    -O3 -march=i686    -o CMakeFiles/cmTC_41dd1.dir/testCCompiler.c.o   -c /home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
 #ifdef __cplusplus
 ^
/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp/testCCompiler.c:1:0: error: CPU you selected does not support x86-64 instruction set
CMakeFiles/cmTC_41dd1.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_41dd1.dir/testCCompiler.c.o' failed
make[1]: *** [CMakeFiles/cmTC_41dd1.dir/testCCompiler.c.o] Error 1
make[1]: Leaving directory '/home/alan/Documents/kcov/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_41dd1/fast' failed
make: *** [cmTC_41dd1/fast] Error 2

'''

**Comment by SimonKagstrom** [comment]
What compiler is /usr/bin/cc then? What OS are you running? Very strange problem I must say!

**Comment by huangshiyou** [comment]
OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

cc:
cc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

I have no idea what is wrong. But after I reboot the system and execute cmake .. again, everything works well now.

**Comment by SimonKagstrom** [comment]
OK, nice that it works again! Closing the report.
