### ISSUE TITLE
kcov with python unittest discover

### ISSUE THREAD

**Issue by Fatlog** [SimonKagstrom/kcov#238]
Hi,

I'm trying to use kcov to report on my python unit test coverage.
I'm running the following...

kcov /tmp/results python -m unittest discover -s test -p '*_test.py'

And it runs fine. However when I inspect the output it looks like its only reporting on the actual python executable and its related dependencies and not the actual unit test code. So my report contain...

python2.7 46.7% ...

and drilling into it shows things like...

/usr/include/x86_64-linux-gnu/bits/syslog.h ...
/usr/include/x86_64-linux-gnu/bits/stdlib.h ...
etc...

No sign of any of my code or unit tests.

Am I calling it correctly?

Also, Some of my unit tests actually call bash scripts using "subprocess.Popen".
Is it likely that these bash scripts would also be reported on?

Thanks!

**Comment by SimonKagstrom** [comment]
Well, this I must admit is a thing I didn't think about. You pass "kcov" instead of python as the command, but you have some extra options to the Python executable itself which can't be passed to kcov.

You can use `--python-parser=cmd`, but I doubt that it will work with the extra options (`-m unittest` etc)

**Comment by Fatlog** [comment]
I tried running with "--python-parser=cmd" but it seems to kill the script. I get a "Killed" message fairly soon after starting.

I'm not necessarily tied to this method of calling my tests either.
Would there be an alternate method of calling it that might work? (preferably keeping the "discover" feature).

**Comment by SimonKagstrom** [comment]
The idea with --python-parser is to specify e.g., /usr/bin/python2.7
instead of the default. It could be worth passing your command line in full
in place of cmd, but im not sure it will work.

Or perhaps this is what you tried?

**Comment by Fatlog** [comment]
Sorry. I misunderstood. So I dropped in "--python-parser" as follows...

kcov --python-parser=/usr/bin/python /tmp/results python -m unittest discover -s test -p '*_test.py'

Assuming this is correct. The test run exited after while with "kcov: error: Too much solib data read".

The generated reports had a lot more scripts reported on but strangely not any of my own repository. It reported on all the other third party libraries I call through my tests but not my own code?!

Separately I also tried running the tests using nose which all ran fine. I then ran...

kcov /tmp/results nosetests 

This actually did report on my own code but a lot of the tests also failed due to missing modules which I am assuming might be related to...

https://github.com/SimonKagstrom/kcov/issues/32

**Comment by SimonKagstrom** [comment]
You probably need to quote the argument to `--python-parser`, i.e.,
```
kcov --python-parser="/usr/bin/python /tmp/results python -m unittest discover -s test" /tmp/kcov first_test.py
```

And then start with a test at a time. I'm still not sure it will work though, but worth a test.

**Comment by Fatlog** [comment]
Doesn't seem to be playing nice for me. It keeps hanging :(

**Comment by Fatlog** [comment]
ok, so i've switched to using nose to run the tests and I'm able to get most of the data I want this way. I needed to explicitly include some of the modules in my tests but thats not a big change.
This leaves me with a couple of other questions (which should probably be in a separate issue)...

1. Can I report on scripts that are not covered by tests? i.e. script1.py - coverage 0%. 
So that I can more easily see which files are being omitted from my tests

2. Does kcov return (or can I extract) the main code coverage percentage to display after the tests run?
i.e. it runs and spits out "78% code covered"

**Comment by Fatlog** [comment]
Also, I only see the Python scripts that ran. Is it possible to see the bash scripts that may have been kicked off from within a Python script?

Thanks

**Comment by SimonKagstrom** [comment]
As for 1. above, the same solution as for #224 (also reported by you!) should be fairly easy to implement.

Number 2 should also be fairly easy to implement.

Unfortunately though, it would be quite tricky to cover cross-language (i.e., the bash scripts). That's similar to #206.

**Comment by Fatlog** [comment]
Great!. Thanks Simon. I thought I had posted something similar a while back but couldn't find it again!
