### ISSUE TITLE
fork tests reverse parent-child relationship

### ISSUE THREAD

**Issue by asomers** [SimonKagstrom/kcov#251]
Several tests call `fork(2)` but reverse the parent-child relationship.  Usually it's just an inconsequential goof in the output text.  But it can also change the intended behavior of the program.  For example, tests/fork/fork.c intends to create a process with a child and a grandchild.  Instead, it creates a process with two children.  That may be reducing the value of the testcase.  I haven't audited them all.

**Comment by SimonKagstrom** [comment]
Fixed with 5a5c07c.

Thanks and good catches!
