### ISSUE TITLE
Document merging output for the github README.md

### ISSUE THREAD

**Issue by eugpermar** [SimonKagstrom/kcov#255]
Suites like gcov works well if I execute many binaries (or the same binary with different arguments) in parallel, does kcov support this too? In particular, I'm interested in bash coverage.

For example, to have two scripts that source common.sh, and I execute them in two different shells, will the common.sh merged reports be OK? If not, what parts of kcov should be modified to support it?

Thanks and regards!

**Comment by SimonKagstrom** [comment]
Yes, it merges the output of several runs if you use the same output directory. I.e.,

```
kcov /tmp/kcov src/script_a.sh  # Includes common.sh
kcov /tmp/kcov src/script_b.sh  # Also includes common.sh
```

you will see a `[merged]` link in the output, which contains the union of `script_a.sh` and `script_b.sh` coverage. If `common.sh` is sourced from both, the merged coverage result will be present in `[merged]`.


kcov can also merge multiple output directories into one via the `--merge` option.


I'll leave the report open until this is clarified better in the online documentation.

**Comment by eugpermar** [comment]
Sorry, I wasn't clear enough. I was meant to run kcli under GNU parallel or `make -j`, to have >1 parallel running instances of kcov at the same time, outputting at the same directory.

Of course, I could generate the output in different directories (out_a, out_b) and then merge, that would work for me, but maybe that parallel execution is a valid use case that would make my life easier.

**Comment by SimonKagstrom** [comment]
OK, sorry, I didn't understand then.

Probably it won't work very well, since I don't remember really adding file locking. If you require something like this, it's probably best to output to multiple directories and then merge them with `--merge` when all subtasks are ready.

**Comment by eugpermar** [comment]
:+1:  cool enough then :) I let the issue open for documenting `--merge` feature! Thanks!

**Comment by cattanimarco** [comment]
What if the parallel runs are more than 1000? Is it possible to merge directories using a regexp?

**Comment by SimonKagstrom** [comment]
Wow, that was quite a scalability test!

I've updated the documentation, so now closing this (by now forgotten) bug.
