### ISSUE TITLE
Mac OS X 10.13.4 - CMake Error: Xcode 1.5 not supported

### ISSUE THREAD

**Issue by eedwards-sk** [SimonKagstrom/kcov#261]
```
→ cmake -G Xcode ../
CMake Error:
  Xcode 1.5 not supported.
```

**Comment by SimonKagstrom** [comment]
Well, I'm unfortunately no OSX expert, but there are apparently some workarounds to be found:

https://wiki.vcmi.eu/How_to_build_VCMI_(macOS)

another alternative is to build using make, which works fine for me but some people have problems with. In that case, build as

```
cmake ../
make
```

**Comment by eedwards-sk** [comment]
Hah, thanks, that's the only site I found referencing the error, as well.

I'll try with make.

**Comment by eedwards-sk** [comment]
Building with make worked, thank you!
