### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by kannaiah** [SimonKagstrom/kcov#262]
Kcov SHA: c630aa47b4840fb73224276cadd3b29a319cdf1f

System information:
```
uname -a
Linux kanna-virtual-machine 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Build commands:
```
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr  ..
make -j2
```

Error message:
```
/mnt/hgfs/vm-share/kcov/src/engines/system-mode-binary-lib.cc:1:23: fatal error: sys/types.h: No such file or directory
compilation terminated.
src/CMakeFiles/kcov_system_lib_32.dir/build.make:62: recipe for target 'src/CMakeFiles/kcov_system_lib_32.dir/engines/system-mode-binary-lib.cc.o' failed
make[2]: *** [src/CMakeFiles/kcov_system_lib_32.dir/engines/system-mode-binary-lib.cc.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'src/CMakeFiles/kcov_system_lib_32.dir/all' failed
make[1]: *** [src/CMakeFiles/kcov_system_lib_32.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Built target kcov_system_lib
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SimonKagstrom** [comment]
Well, I've broken the build while trying to fix #256. Works for me but not on travis or for you.

Probably fixed by reverting

fdfbfb3a29f3dcc7d6fbadd221b7843f06b86bf7

otherwise the entire series will have to be reverted...

**Comment by kannaiah** [comment]
Although it is building 64 target, 32bit libs are required.
Looks like I didn't have 32 bit libs not installed properly.
After installing I was able to build 
```
apt-get install gcc-multilib g++-multilib
```

**Comment by SimonKagstrom** [comment]
I've reverted the broken commit with 500a707, so closing this and hoping it will stay closed :-)

#256 was there to build a 32-bit version of the system-mode library, even on 64-bit systems, but I think it will require more cmake magic in order to detect if 32-bit build support is actually present first.
