### ISSUE TITLE
Problem when detecting capabilities

### ISSUE THREAD

**Issue by stevengubler** [SimonKagstrom/kcov#263]
I just got kcov built and installed, but I'm running into an issue where kcov won't do anything other than report that I don't have the 64bit capability:
```
kcov: error: Capability 64bit not present
```
I'm assuming that this is referring to my CPU's capabilities. However, if you notice when I run `lscpu | grep 'CPU op-mode'`, my cpu is definitely 64bit:
```
CPU op-mode(s):      32-bit, 64-bit
```
I did try building from `fdfbfb3` as indicated in #262, but it hasn't changed anything.

It looks to me like kcov is detecting my capabilities incorrectly.

**Comment by SimonKagstrom** [comment]
I believe this should now be fixed by the same revert as for #262, it was a regression which came while trying to fix #256.
