### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by barsan-md** [SimonKagstrom/kcov#265]
This utility is no more available in Ubuntu 18.04, for some reasons. Did anyone consider creating a snap package (or flatpack if you prefer)?. That would make it available for the whole linux ecosystem.

**Comment by SimonKagstrom** [comment]
I'm not sure. I don't know snap packages myself, so have no idea about how to create one.

The Debian package was not kept up to date, version-wise, so perhaps that's why they dropped it.


There are docker builds for kcov, if that helps.

**Comment by barsan-ds** [comment]
I managed to correctly install the docker image and run it using
```docker run...```
Now my problem maybe is not directly relevant but I cannot managed to run kcov from automatic tools (like CMake).

I created an alias
```alias kcov="docker run..."```
In the bashrc file but it doesn't word outside the terminal emulator.

In general snap/flatpack is much easier from a dump user point of view.
Do you have suggestions?

**Comment by gocarlos** [comment]
I can take on this one as i have packaged already some apps as snaps... would be happy to contribute if you like

**Comment by SimonKagstrom** [comment]
Thanks a lot @gocarlos and @barsan-ds !

**Comment by williamdes** [comment]
I think we should close this as I will refresh the Debian package soon
See #444 
https://tracker.debian.org/pkg/kcov
