### ISSUE TITLE
Bash script source not available on Coveralls.io

### ISSUE THREAD

**Issue by kimkim19642004** [SimonKagstrom/kcov#270]
Dear Mr.Simon Kagstrom,

I ran the following command on Travis-CI.com, but I could not see Bash script source code 'po2bats.sh' on Coveralls.io:
kcov --coveralls-id=$TRAVIS_JOB_ID --include-pattern=po2bats.sh ./tests/coverage po2bats.sh

The coverage of 'po2bats.sh' is displayed as 100%.
I am seeking your advice. I don't know what is wrong. Should I debug kcov?

My source codes, README.md and .travis.yml location:
https://github.com/kimkim19642004/po2bats-autotools

Note:
Click the badge pasted in README.md in order to view the coverage.

Very truly yours,

Katsunari Kimura (Japanease)

**Comment by SimonKagstrom** [comment]
Is `po2bats.sh` generated? In that case, travis won't find it on github since it only shows up in the build process.

**Comment by kimkim19642004** [comment]
You're right!

'po2bats.sh' is a shell script generated from 'po2bats.sh.in'.

Oh! ... I am stupid!

I am grateful to you!
