### ISSUE TITLE
Bash script prompt/expect/read doesn't work properly

### ISSUE THREAD

**Issue by christronyxyocum** [SimonKagstrom/kcov#271]
Very new to all of this and taking on the adventure of trying to get my bash script to at least 75% coverage just because.

I'm using Travis CI and Codecov for this process and, within Travis, I'm using some expect scripts to handle a few prompts for various options of the script, but I can't seem to get them to play nice with kcov.

How can I use kcov to handle script options that prompt the user for input?

**Comment by SimonKagstrom** [comment]
I haven't tried that before, and indeed it doesn't work. Probably kcov needs to pass stdin on to the shell script for this to work. I believe what you are seeing is kcov trying to gobble up the input instead of the script.

**Comment by christronyxyocum** [comment]
Alright, thanks, so I guess I'll just have to be proud of my 52% for the time being, haha.

**Comment by christronyxyocum** [comment]
Could it be possible to have kcov run a wrapper shell script that executes an expect script?
