### ISSUE TITLE
docker images are stale

### ISSUE THREAD

**Issue by mmlb** [SimonKagstrom/kcov#273]
The latest version on https://hub.docker.com/r/ragnaroek/kcov/ is stale, only has v33 as latest. I've gone ahead and registered the kcov org on docker hub since imo it seems nicer to either pull from a more official looking org/image (kcov/kcov) or from same layout as github (SimonKagstrom/kcov).

I'd like to fixup the sync to hub too, either continuing on with docker automatic builds or pushing from travis. I'm not sure which is preferable. But imo docker build source should be in this repo (similar to `debian` folder). Either way I'd like to set it up so docker tags are matched to git tags and docker image's `latest` tag corresponds to `master` branch.

**Comment by SimonKagstrom** [comment]
Yes, that sounds like a good idea. I'm not personally involved in the docker image generation, and really don't know enough about it or docker hub to be of much help though.

I'd be happy to accept a pull request with the docker build source!

**Comment by SimonKagstrom** [comment]
For me it doesn't matter (probably mainly because I don't know the implications :-) ). What would you say is the cleanest approach?

**Comment by mmlb** [comment]
docker hub building automatically is probably the cleanest way (repo wise), since you only have to add the Dockerfile vs both Dockerfile and supporting code to travis scripts + creds.

**Comment by SimonKagstrom** [comment]
OK, then that sounds like the way to go!
