### ISSUE TITLE
Using kcov with c++ unit tests

### ISSUE THREAD

**Issue by devashish2203** [SimonKagstrom/kcov#276]
I was trying out kcov as an alternate to our already existing gcov/lcov setup and could not figure out how to generate a combined report for my code base, after running all unit tests binaries.

We usually run all the unit tests with `make test` and then run gcov and lcov to gather the coverage reports.

With kcov I find that the only option is to run each unit test binary individually with the same output folder, to achieve a similar report (Atleast I hope it would be similar).

Is there some support to run all test binaries with kcov like `make test` does?

**Comment by SimonKagstrom** [comment]
Can you control what the Makefile does in `make test`? In that case, you could run kcov from there. That's basically what we do on my workplace.

Other than that, I suppose you could make a clever script :-) I.e., something like

```find <bindir> -type x | xargs -n 1 kcov <out-dir>```

(not completely sure about the shell syntax though)

**Comment by devashish2203** [comment]
Yeah, I'm using a script to run all the unit test binaries for now..

```
#!/bin/bash

pushd <BuildDirectory>
for line in `make help`
do
    if [[ ${line} =~ "_test" ]]
    then
        rel_path_bin=$(find . -iname "${line}")
        if [[ ! -z ${rel_path_bin} ]]
        then
            test_dir=$(dirname $(readlink -f ${rel_path_bin}))
            pushd ${test_dir}
            kcov --verify "<Output>" ./${line}
            popd
        fi
    fi  
done
popd
```
Will look into integrating this with our cmake if we start using kcov in our workflow. Thanks :)

**Comment by SimonKagstrom** [comment]
OK!

A tip is to use the `--include-pattern=` and/or `--exclude-pattern` feature, since it's typically only a subset of the sources which are interesting to include in the reports. We exclude non-company code and also the test drivers themselves.
