### ISSUE TITLE
I tested the command line parsing process inside 'kcov'.

### ISSUE THREAD

**Issue by kimkim19642004** [SimonKagstrom/kcov#290]
Dear Mr.Simon Kagstrom, **kcov** is really useful !!

I am using **kcov** to test my bash scripts under the FreeBSD environment shown below:

| Difficulty (highest first) | Environment | kcov working status |
| --- | --- | --- |
| 1 | [Cirrus CI](https://cirrus-ci.org/) FreeBSD (version 11/12) | The message 'kcov: error: Can't find or open <file>' was displayed. See [Error logs](https://cirrus-ci.com/github/kimkim19642004/po2bats-autotools). |
| 2 | GhostBSD (version 19) on my old Laptop-PC | **kcov** has no problem. Desktop-system is unstable. |
| 3 | FreeBSD (version 12) on my old Laptop-PC | The message 'kcov: error: Can't find or open <file>' was displayed once, but I have not been able to reproduce the phenomenon. |
| 4 | GhostBSD (version 18) on my old Laptop-PC | No problems |

#### TODO:
- I want to get the green badge!! of [Cirrus CI](https://cirrus-ci.org/).
- Test and code review for [configuration.cc](https://github.com/SimonKagstrom/kcov/blob/master/src/configuration.cc).
- Clearly separate the processing for **'optional arguments'** and **'file operands'**. See [the sample codes of getopt(3)](https://man.cx/getopt(3)).

#### Reference
- [Error logs](https://cirrus-ci.com/github/kimkim19642004/po2bats-autotools)
- [.cirrus.yml](https://github.com/kimkim19642004/po2bats-autotools/blob/master/.cirrus.yml)
- [debug main.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/main.cc) -> See comment marks: kimkim19642004
- [debug configuration.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/configuration.cc) -> See comment marks: kimkim19642004

#### Remarks
There is no problem with the following platforms:
Fedora/Ubuntu/openSUSE/macOS

Thank you.

**Comment by SimonKagstrom** [comment]
Could it be a path problem? I.e., is the po2bats.sh script really in the current directory?

Does the behavior change if you run kcov with the full path to po2bats.sh?

**Comment by kimkim19642004** [comment]
Dear Mr.Simon Kagstrom, 

I enjoy using the latest version 'kcov v36-29-gb227' now.

Q1) Is the **po2bats.sh** script really in the current directory?

No, **po2bats.sh** does not exist in the **current directory**.

I checked it inside kcov using the following source code:
[debug configuration.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/configuration.cc) -> See 'Line 549-557'

I thought **kcov** would find **po2bats.sh** using the environment variable **PATH**. But it seems to be my mistake.

Q2) Does the behavior change if you run kcov with the full path to **po2bats.sh** ?
Yes, It has changed! **kcov** recognized the existence of **po2bats.sh**.

I checked it inside kcov using the following source code:
[debug main.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/main.cc) -> See 'Line 216-217'

I will modify the **po2bats.sh** test program to specify the full path.

#### Finally:

By the way, a tool called [shellcheck](https://github.com/koalaman/shellcheck) also needs full path specification.
Therefore, I think now that asking **kcov** to check the environment variable **PATH** is an over-demanding requirement.

Thank you.

**Comment by SimonKagstrom** [comment]
Well, it is supposed to use PATH to look up the binaries, so that is a bug. It might perhaps be bash-specific, because I'm pretty sure it works with regular binaries. Good that you found a workaround anyway!

**Comment by kimkim19642004** [comment]
Thank you for your reply. I close this issue.

I'm sure only Mr.Kagstrom's padron (for the **professional version** of kcov) can shout **this is a bug!**  :laughing:

Wish good luck!

**Comment by SimonKagstrom** [comment]
:-) it sounds like a bug, but perhaps there's some difference with bash which I didn't think about.

**Comment by kimkim19642004** [comment]
Dear Mr.Simon Kagstrom,

I have the same opinion as you. Please wait while I report more detailed logs...

#### Filter the cause:
configuration.cc(517): printf("%s(%d): before get_real_path()=%s\n", __FILE__, __LINE__, path.c_str());
configuration.cc(518): path = get_real_path(path);
configuration.cc(519): printf("%s(%d): after get_real_path()=%s\n", __FILE__, __LINE__, path.c_str());

#### Result:
configuration.cc(517): before get_real_path()=po2bats.sh
configuration.cc(519): after get_real_path()=po2bats.sh

This is my unexpected result!

#### Code Review of get_real_path():
utils.cc(536): char *rp = NULL;
utils.cc(537):
utils.cc(538): rp = ::realpath(path.c_str(), NULL);
utils.cc(539):
utils.cc(540): if (!rp)
utils.cc(541):   return path;

Isn't it necessary to call free(rp) at utils.cc(541) ?

Please wait while I report more detailed logs...

Thank you.

**Comment by kimkim19642004** [comment]
Dear Mr.Simon Kagstrom,

I noticed that this problem is unsolved. At last, I found the cause of this problem!
Please let me know how to solve the following problems:

#### Main point:
- On FreeBSD, std::ifstream::read() succeeds for the specified directory.
- On non-FreeBSD, std::ifstream::read() fails for the specified directory.

#### References:
- [debug bash-engine.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/bash-engine.cc)
- [debug utils.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/utils.cc)
- [debug parser-manager.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/parser-manager.cc)
- [debug configuration.cc](https://github.com/kimkim19642004/po2bats-autotools/blob/master/configuration.cc)
- [ERROR LOG](https://cirrus-ci.com/task/6285225647144960) -> Search by the keyword **'is directory'**

#### Remarks:
Apart from this problem, there is also a problem with **administrator rights**.
The scope of that problem: Fedora/Ubuntu/macOS/openSUSE/FreeBSD, etc.
I will report it on another occasion.

Thank you.

**Comment by kimkim19642004** [comment]
I close this issue. I appreciate your work.

Good luck!
