### ISSUE TITLE
Bash on macOS: Failed to exchange stderr for pipe.

### ISSUE THREAD

**Issue by kimkim19642004** [SimonKagstrom/kcov#293]
Dear Mr.Simon Kagstrom,

Please tell me the solution to the following problems:

|Items|Description|
|---|---|
|phenomenon|When I run **kcov** on macOS, it says _**"Failed to exchange stderr for pipe"**_.|
|causing|**The maximum number of file descriptors** specified inside of **kcov** is larger than the system value.|
|Error log|https://travis-ci.com/kimkim19642004/po2bats-autotools/jobs/199193095#L2853|
|**One proposal for solving this problem**|https://github.com/kimkim19642004/po2bats-autotools/blob/master/bash-engine.cc#L140-L149|
|Impact range|Mac OS X 10.13/10.14|
|Remarks|See https://man.cx/getrlimit|

I look forward to hearing from you.

**Comment by SimonKagstrom** [comment]
Sorry for not replying yet!

The solution looks solid, so please submit a pull request for it!

**Comment by kimkim19642004** [comment]
Thank you for the merge. I close this issue.
