### ISSUE TITLE
How to find a valid BASH_XTRACEFD maximum

### ISSUE THREAD

**Issue by kimkim19642004** [SimonKagstrom/kcov#297]
Dear Mr.Simon Kagstrom,

I encountered the following bug on **FreeBSD 11/12**:

#### Error Log:
```
+/usr/local/bin/bash: BASH_XTRACEFD: 116972: cannot open as FILE
+kcov@/home/test/po2bats-autotools/tests/coverage/bash-helper.sh@4@set -x
+kcov@/usr/home/test/po2bats-autotools/src/po2bats.sh@40@_org_fname=po2bats.sh
```
#### Notable Bash Code (Error Location):
See https://github.com/kimkim19642004/po2bats-autotools/blob/master/variables.c#L6270-L6274
#### Error Workaround:
It worked well if I limited the number of open files with the command **'ulimit'**.
See https://github.com/kimkim19642004/po2bats-autotools/blob/master/.cirrus.yml#L47
#### Consideration:
Should **kcov** find the value of **BASH_XRACEFD** with the function **fdopen(fd,"w")** ?
See https://github.com/SimonKagstrom/kcov/blob/master/src/engines/bash-engine.cc#L140-L149
Is there a better way?
#### Remarks:
See https://man.cx/fopen

I look forward to hearing from you, thank you.

**Comment by SimonKagstrom** [comment]
Hmm... I'm not sure I understand, is the FD larger than what's returned by getrlimit?

**Comment by kimkim19642004** [comment]
When BASH_XTRACEFD=**116972**, the value of **rlim_cur** was **116972+1**.

This problem can also be reproduced on my laptop computer (FreeBSD 12).

**Comment by SimonKagstrom** [comment]
OK, but what values are OK, i.e., can it be set to rlimit_cur / 2?

**Comment by kimkim19642004** [comment]
Dear Mr.Simon Kagstrom,

The following code was tested but no problem was found.
See https://github.com/kimkim19642004/po2bats-autotools/blob/master/bash-engine.cc#L148

#### Platforms:
FreeBSD 11.2/12.0
Ubuntu 16.04/18.04
Mac OSX 10.13/10.14
OpenSUSE(Tumbleweed)
Fedora30

#### Remarks:
I did not use the command **'ulimit'** at all after a clean install of the above Platforms.

**Comment by SimonKagstrom** [comment]
OK, yes I think that fix should be good with a pull request!

Thanks a lot, and excellent analysis as always!

**Comment by kimkim19642004** [comment]
Good condition! Arigatō
