### ISSUE TITLE
cover C extension of  pt=ython module  with python3.5-dbg segfault  

### ISSUE THREAD

**Issue by davidtazy** [SimonKagstrom/kcov#300]
ubuntu 16.04 32 bits
kcov --version -> 35

I  would like to cover code of  python module C extension 
#206  suggest to use python interp with debug symbols.

`
> kcov cov/ /usr/bin/python3.5-dbg 
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
kcov: Process exited with signal 11 (SIGSEGV) at 0xb7fe0abd
`
`
> kcov cov/ /usr/bin/python3.5-dbg myscript.py
kcov: Process exited with signal 11 (SIGSEGV) at 0xb7fe0abd

`
immediatly crash

I maybe missunderstand something,  I thought python3.5-dbg was python binary with symbols

**Comment by SimonKagstrom** [comment]
Well, that *might* cover the extensions, but I'm not quite sure how python loads them.

It might be the same issue as in #82, and then you should add `--verify` to the kcov command line. However, you're probably not very interested in the Python interpreter sources itself, so add `--include-pattern=path-to-where-your-extension-sources-are` to limit collection.

**Comment by davidtazy** [comment]
--verify did the job!
and its working with standard version of  python, (/usr/bin/python3)
maybe its an hidden feature you could promote
thx you

**Comment by SimonKagstrom** [comment]
Well, the Python 3 stuff is probably due to the fix in #250 .

As for verify, it would be good to have enabled by default, but unfortunately it decreases performance by quite a lot. It's also mainly needed for Rust programs, only sporadically for other languages.
