### ISSUE TITLE
Version number is not set correctly in CMakeList.txt

### ISSUE THREAD

**Issue by oliv3r** [SimonKagstrom/kcov#301]
While this can't be fixed for v36, this should be watched out for in v37. Maybe set it to v37 to prepare for the next version ;)
https://github.com/SimonKagstrom/kcov/blob/master/CMakeLists.txt#L4

**Comment by SimonKagstrom** [comment]
Hehe, I had forgot about that one! Surprised it's at v35 and not v14 or something :-)

If it's really needed, I think it would be good to automate this instead, i.e., in the same way as `--version` is handled:

https://github.com/SimonKagstrom/kcov/blob/master/src/CMakeLists.txt#L43
