### ISSUE TITLE
Python 2 EOL

### ISSUE THREAD

**Issue by Dridi** [SimonKagstrom/kcov#305]
Hi,

With Python 2 going EOL soon, it will become impossible to build the test suite starting with Fedora 31 without patching the source tree. Fedora switched /usr/bin/python to python3, so existing scripts (like `tests/multi-fork/generate-functions.py`) are starting to fail.

I think shebangs should move from the un-versioned `#!/usr/bin/env python` to an explicit `#!/usr/bin/env python2` and ideally ported to Python 3 immediately for simple scripts to eventually drop Python 2 support altogether.

Depending on your interest, I may open a pull request to version the shebangs, and maybe move trivial scripts to Python 3.

**Comment by SimonKagstrom** [comment]
Ah! Yes, the test scripts are probably pretty clumsily written (I'm very much not a Python expert!), so I guess that should be done.

In the short term, I think you python2-shebang is probably best, and then the scripts can be converted one by one.

**Comment by Dridi** [comment]
Shebangs are done in #306. With this I can run the test suite on the upcoming Fedora 31.

On Fedora 30 I get the following redacted results:

```
[...]
runTest (compiled.address_sanitizer_coverage) ... Clang-only
unexpected success
[...]
runTest (bash.bash_coverage_debug_trap) ... unexpected success
[...]
runTest (system_mode.system_mode_can_record_and_report_binary) ... x86_64
ERROR
unTest (system_mode.system_mode_can_start_and_stop_daemon) ... ok
runTest (compiled.vfork) ... ok

======================================================================
ERROR: runTest (system_mode.system_mode_can_record_and_report_binary)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dridi/src/kcov/tests/tools/system_mode.py", line 65, in runTest
    dom = parse_cobertura.parseFile(testbase.outbase + "/kcov-report/main-tests/cobertura.xml")
  File "/home/dridi/src/kcov/tests/tools/parse_cobertura.py", line 46, in parseFile
    dom = xml.dom.minidom.parseString(readFile(filename))
  File "/home/dridi/src/kcov/tests/tools/parse_cobertura.py", line 9, in readFile
    f = open(name,'r')
IOError: [Errno 2] No such file or directory: '/tmp//kcov-report/main-tests/cobertura.xml'

----------------------------------------------------------------------
Ran 85 tests in 80.653s

FAILED (errors=1, expected failures=7, unexpected successes=2)
```

FYI I currently have bash 5.0.7 and gcc 5.1.1 on my system.

**Comment by SimonKagstrom** [comment]
Well, there are some unfinished stuff (the address sanitizer and system mode), which might or might not work. I guess those tests might be best to disable for now.

The debug trap test might perhaps succeed with newer bashes, so that might actually be good :-)
