### ISSUE TITLE
Too much solib data read

### ISSUE THREAD

**Issue by unphased** [SimonKagstrom/kcov#317]
Hi. I have tested versions 38, 37, 36, and all produce this "Too much solib data read" error. I have tried a few simple attempts to debug this by replacing the 1MB array on the stack with a 100MB vector to no avail, and neither does trying to call `fprintf(stderr)` from inside that `solibThreadParse()` method... 

Tested on trivially small C++ programs, kcov works great. It seems to clearly be having issues dealing with large programs loading large shared objects. Any ideas? Surely limiting to 1MB shared object loading is a limitation, especially considering that this architecturally requires using executables with debug info, which are very large.

Ubuntu 18.04

**Comment by unphased** [comment]
Actually i think my hack was done wrong. By turning buf into a pointer, checking its sizeof became wrong. 

It's executing a lot further along now...

**Comment by SimonKagstrom** [comment]
Well, if you're not interested in instrumenting the actual solib code, you can run with --skip-solibs, which will make shared libraries non-instrumented.

Anyway, I'm not quite sure why it would return more data from read() - the buffer size should be the maximum anyway, so something is fishy here. Perhaps add a printout of r if the panic happens

**Comment by unphased** [comment]
Things do seem to work with --skip-solibs but i think since most of the application code is in shared object libraries it's not really practical. 

The buffer is 1 megabyte, now, I have no idea what the pipe is supposed to be that it's reading out of, but I have seen many a shared object larger than that size before.

**Comment by unphased** [comment]
Maybe read is returning `-1`?

**Comment by SimonKagstrom** [comment]
The pipe is used to communicate information about how the solibs are loaded into memory (see solib-parser/lib.c), so it surprises me that it can be that big anyway. The data is not the libraries themselves, just information about "program headers" in them.

Anyway, I suppose the read should really be done in a loop instead, to be able to handle the case where lots of data is written without panic. Then it would gather data to a growing buffer instead, and the size of the read destination would be irrelevant.

**Comment by nate-thirdwave** [comment]
Noting that this keeps biting us still these days.  It seems to be related to when we have a fairly deep number of solib deps, but I can't pin it down to anything in particular. Anecdotally, the grpc library dependency seems to be correlated with hitting this in our codebase, but that may be a herring.

**Comment by SimonKagstrom** [comment]
Does the @unphased quick-fix work for you? I suppose the loop implementation would be cleaner, but allocating 100MiB these days shouldn't be a very big problem anyway.

**Comment by katarinabouma** [comment]
yes, we got the @unphased fix working for us today (I work with @nate-thirdwave).

**Comment by SimonKagstrom** [comment]
Nice, thanks! Care to submit a PR for it (maybe with --author=@unphased )? I think it should be a fine work-around.

**Comment by unphased** [comment]
I can make a PR. Let me get back up to speed with this.. I don't remember what this was about. I think I was using this for work at my last job.
