### ISSUE TITLE
any way to add cucumber tests to the coverage ?

### ISSUE THREAD

**Issue by omallassi** [SimonKagstrom/kcov#320]
Hi,

First of all thanks for this tool! I 
On my side (quite new to Rust) but I am using [rust-cucumber](https://github.com/bbqsrc/cucumber-rust) for some tests. basically these tests are run with `cargo test`

yet, when Kcov runs the tests, it looks like cucumber tests are not ran. 

I was wondering if, given current Kcov version, there would be a way to add this coverage information to the reports?

**Comment by SimonKagstrom** [comment]
Unfortunately I don't know rust, but in general, kcov needs to run on the binary, so if rust-cucumber is some sort of wrapper, it needs to invoke kcov. Hopefully some Rust-literate person can help you here!

**Comment by SimonKagstrom** [comment]
Unfortunately I don't know rust, but in general, kcov needs to run on the binary, so if rust-cucumber is some sort of wrapper, it needs to invoke kcov. Hopefully some Rust-literate person can help you here!

**Comment by omallassi** [comment]
thx for your time and answer. you are right, this is much more a rust question :) apologies.
