### ISSUE TITLE
Latest kcov release (38) returns wrong version

### ISSUE THREAD

**Issue by cattanimarco** [SimonKagstrom/kcov#329]
When running 
`kcov --version`
on release 38 the following is returned 
`kcov v37-11-g7cba`

Is should be updated to v38 I believe

**Comment by SimonKagstrom** [comment]
I'm not quite sure why actually, it's CMake magic which I don't really understand. :-)

**Comment by SimonKagstrom** [comment]
Closing this, should be fixed with the next version.
