### ISSUE TITLE
Kcov reports 0% on bash scripts when running as root.

### ISSUE THREAD

**Issue by Orycterope** [SimonKagstrom/kcov#331]
Since Bash 4.4, you cannot set PS4 in the environment when running as root, due to security issues:

> 56. Bash-4.4 does not inherit $PS4 from the environment if running as root.

https://github.com/bminor/bash/blob/d233b485e83c3a784b803fb894280773f16f2deb/COMPAT#L383

But this is the way kcov does it, setting PS4 in the environment and then calling `/bin/bash -x <desired script>`. Which means kcov does not work when running as root. PS4 is not taken from the environment, and defaults to '+'. From there, kcov sees no PS4 line starting with `kcov@...` and reports that no line has been covered, hence the 0%. 

This is an important bug, because it affects the docker image that you provide, since in it kcov is run as root. Had me believe kcov did not work on bash at first, until I compiled it myself and tested it as an unprivileged user. 

What I propose to do is to set the PS4 in the `bash-helper.sh` that is sourced at the beginning instead, and stop setting it in the environment. 

I'm creating a PR which does just that.

**Comment by SimonKagstrom** [comment]
OK, that sounds like a reasonable solution.

I actually believe the debug trap mode works as root though, but that has some other issues which makes it unsuitable.
