### ISSUE TITLE
Temporary macOS 10.15 build instructions due to Issue #166

### ISSUE THREAD

**Issue by kimkim19642004** [SimonKagstrom/kcov#336]
What is missing to do the basic build instructions(cmake->make->make install) on the **macOS 10.15** build environment of [Travis CI](https://travis-ci.com/)?

 :cry: Please tell me if you know  :cry:

Reference: [Installing on OSX, kcov can't find LLDB #166](https://github.com/SimonKagstrom/kcov/issues/166)

### The following temporary build instructions are still required on the macOS 10.15 build environment of [Travis CI](https://travis-ci.com/):

`OPENSSL_ROOT_DIR=$(brew --prefix openssl)`
`export OPENSSL_ROOT_DIR`
`cd $HOME`
`git clone https://github.com/SimonKagstrom/kcov.git`
`cd kcov`
`mkdir build`
`cd build`
`cmake -G Xcode ..`
`xcodebuild -target kcov -configuration Release`
`cp src/Release/kcov /usr/local/bin`

### The following is the basic build instructions for 'kcov' that was successfully built on the macOS 10.13/10.14 build environment of [Travis CI](https://travis-ci.com/):

`OPENSSL_ROOT_DIR=$(brew --prefix openssl)`
`export OPENSSL_ROOT_DIR`
`cd $HOME`
`git clone https://github.com/SimonKagstrom/kcov.git`
`cd kcov`
`mkdir build`
`cmake ..`
`make`
`make install`

**Comment by SimonKagstrom** [comment]
Yes, the OSX travis builds have been broken for quite some time.

It's probably some dependency which has changed since openssl isn't found.

**Comment by kimkim19642004** [comment]
Dear Mr.Kagstrom,

Thank you for your response.

I also tried building **kcov** on [AppVeyor](https://www.appveyor.com/) and the situation is similar.

There are no fatal problem so far, so I'll close this issue.

Thank you.
