### ISSUE TITLE
arm: inconsistent reported results

### ISSUE THREAD

**Issue by dianpopa** [SimonKagstrom/kcov#337]
HI,

I am trying to enable kcov on aarch64 in [our project](https://github.com/firecracker-microvm/firecracker/) and we keep obtaining different numbers between different runs with no code change. From my investigation it seems that at random times lines are found as executable while some time they are not.
Anybody stumbled upon this problem?

**Comment by SimonKagstrom** [comment]
Not really, unless the project is using threads and unpredictable for that reason. I've not personally used kcov on aarch64, but unless it sometimes fails to report breakpoints, I don't really see what causes this behavior.

One thing, if running multiple runs with the same output directory, is that the results are accumulated, so if the runs depend on user input, a second run would accumulate the output and thus might have higher coverage. This behavior can be avoided with passing `--clean` to kcov.

**Comment by dianpopa** [comment]
We have not seen this issue in a long time. Closing this.
