### ISSUE TITLE
cirrus-ci and coveralls

### ISSUE THREAD

**Issue by rollbear** [SimonKagstrom/kcov#338]
I'm trying out cirrus-ci for my CI builds, but when it comes to reporting coverage from kcov to coveralls.io, I get the following:

```
kcov: warning: coveralls write failed: {"message":"Travis API Error: #\u003cCoveralls::Mash message=\"The job(4822784943587328) couldn't be found\"\u003e. ","error":true}
```

I assume I'm the one doing something wrong here. Why Travis? I naïvely just used `--coveralls-id=...` in the same way I've successfully done with Travis-CI, but using a different environment variable, of course.

**Comment by SimonKagstrom** [comment]
Well, I actually don't remember quite how this integration works, even though I'm pretty sure I wrote it myself a few years ago :-)

There is also a "configuration key" related to coveralls which can be set, which is `coveralls-service-name`, and can be set with

```kcov --configure=coveralls-service-name=XXX [...]```

It's by default set to travis-ci, but perhaps needs to be set to something else for cirrus-ci?

**Comment by rollbear** [comment]
Closing this one since I'm scrapping cirrus anyway. I may have reason to revisit this with some other CI system in the near future.
