### ISSUE TITLE
What's the meaning of the hits number ?

### ISSUE THREAD

**Issue by czlhs** [SimonKagstrom/kcov#341]
![image](https://user-images.githubusercontent.com/17726532/99788776-91eac580-2b5c-11eb-89e4-6f5e1244e75b.png)
for example, the above 6 / 6,  3 / 3, 1 / 1.
Does it means the expression count  or something else ?

**Comment by SimonKagstrom** [comment]
It means the number of breakpoints on a particular line. So for example

```
for (int i = 0; i < 3; i++)
```

has 3 DWARF entries which maps to that line, and 3/3 means that all of them have been hit. Had it been something like

```
int v = 5;
[...]
for (int i = v; i < 3; i++)
```

then probably it would have been 1/3, or 2/3. The compilers sometimes generate confusing results, so it's not always quite easy to determine what generated the DWARF entries (see line 43 for an example).

Bash and Python instead generates a hit count, and merged reports only have a boolean hit/or-not-hit state.

**Comment by czlhs** [comment]
Thanks,  I got it.
