### ISSUE TITLE
How to use --collect-only on remote and --report-only on local ?

### ISSUE THREAD

**Issue by czlhs** [SimonKagstrom/kcov#342]
I use collect-only option on server,  then download the coverage data to my local machine  and use report-only option to get the data, but  the code coverage is 0.0%. do i need to link something or else ?
```shell
 # on my remote server
./kcov --verify   --collect-only cov_data  MY_BIN 
# just then scp it.
tar -zcvpf data.tar  cov_data/                                   

# report on my local machine
./kcov --verify  --report-only cov_data   MY_BIN  
```

**Comment by SimonKagstrom** [comment]
That should work, assuming the binary is the same, and that the source code is available on the local machine (in the path where the binary was built).

What you can do is to run with the debug mode while collecting, i.e.., --debug=31, which should show you that it collects breakpoints as expected. Kcov will then output a "database" file in the cov_data directory, which is read during --report-only.

**Comment by czlhs** [comment]
It can work if I copy the source code to remote server and use report-only.  I copy the compiled kcov from remote server to local machine, maybe there is some library dependency  problem on the local ?

**Comment by SimonKagstrom** [comment]
OK, this is strange. Maybe you can try with --debug=31 on the report-side as well. At least we now know that the collection works as expected.

As long as kcov runs, I don't think there should be a library issue on the local side. Are the environments the same in other ways, i.e., is it the same OS, same machine architecture etc? Is the local machine the build machine?

**Comment by czlhs** [comment]
The OS are same, the local machine are the build machine.
```bash
$ uname  -a
Linux  3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
and if I use debug=31 : 
```
BP registered at 0x81ef80
REPORT ...server.cc:228 at 0x81ef80
REPORT ...server.cc:228 at 0xe458266b06
REPORT ...server.cc:228 at 0xe458266b06
BP registered at 0x81f870
REPORT ...server.cc:228 at 0x81f870
REPORT ...server.cc:228 at 0xe458266b06
REPORT ...server.cc:228 at 0xe458266b06
BP registered at 0x81f880
REPORT ...server.cc:68 at 0x81f880
REPORT ...server.cc:68 at 0x4458266b06
REPORT ...server.cc:68 at 0x4458266b06
REPORT ...server.cc:69 at 0x81f880
REPORT ...server.cc:69 at 0x4558266b06
REPORT ...server.cc:69 at 0x4558266b06
BP registered at 0x81f8d1
REPORT ...server.cc:70 at 0x81f8d1
REPORT ...server.cc:70 at 0x4658266b06
REPORT ...server.cc:70 at 0x4658266b06
BP registered at 0x81f90a
```
It seems code have run here, but the result Executed lines output is still zero.

**Comment by SimonKagstrom** [comment]
OK, then it seems to read the database correctly, and also report the hits correctly.

I guess the source code is where it's expected to be at, i.e., the path to server.cc is readable on the local machine?

**Comment by czlhs** [comment]
I compile the binary on the local machine, and  the source code still exists.

**Comment by czlhs** [comment]
finally I find the reason, The collect directory and the report directory should be same. but most time the build directory which have code file and the the running-server directory which collect the data are not same. should it not depend on the 
 same directory ?
```c++
       // configuration.cc:531, tmp.first is the binary's directory.
	setKey("target-directory",
					fmt("%s/%s.%08zx", outDirectory.c_str(), binaryName.c_str(),
							std::hash<std::string>()(tmp.first)));
```

**Comment by SimonKagstrom** [comment]
Ah, good catch!

I've grown used to always using /tmp/kcov as the output directory, so that probably explains why I didn't see this. So if I understand you correctly, you have basically

* Source directory /a/src/[...]
* Build directory /b/target
* Binary /b/target/bin/server
* kcov report directory /tmp/collected

on the host, and then on the target

* Binary /usr/bin/server
* kcov collect directory /tmp/my-output

? And to get it working, you need kcov report directory and kcov collect directory to be the same?

**Comment by czlhs** [comment]
Yes,  If I collect data   in `/server/cov_data` directory, and I copy the `cov_data` directory to my local machine,  assume it is `/home/xxx/cov_data`. So the `cov_data` 's parent directory should be same: `/server` and `/home/xxx` should be same.
I suggest it shouldn't depend on the same directory, and it should throw an error If `coverage.db` is empty when kcov report only.

**Comment by SimonKagstrom** [comment]
Hmm... I've tried a bit here, not between two machines, but two directories on my host. I don't quite understand why it behaves strangely. Here's what I've observed. I do

```
kcov --collect-only /tmp/kcov /Users/ska/projects/build/calc/calc
 ```

so /tmp/kcov contains the database. Then I do

```
cp /Users/ska/projects/build/calc/calc /private/tmp/calc
cp -r /tmp/kcov /tmp/copy
cp -r /tmp/kcov /tmp/copy2
```

and then run

```
kcov --report-only /tmp/copy /Users/ska/projects/build/calc/calc
kcov --report-only /tmp/copy2 /private/tmp/calc
```

Of these, the first work as expected, but the second one doesn't. What I observe is therefore that the location of the binary is important, but not the directory it was copied from.

I think this might be because of filename hashing (which probably uses the entire directory path to the binary). I'll have to look it up in the source code a bit better.

**Comment by czlhs** [comment]
Yes, It use the hash of the binary directory as the data directory suffix. I always collect and report on current binary's directory ( kcov --report-only  ./cov_data  ./server ). so the collect directory and binary directory is same.

**Comment by SimonKagstrom** [comment]
I believe I've fixed the problem with 4f758b1 above. It's in the branch issue-342-collect-and-report if you'd like to test it.

I've only tested it on OSX (and on a single machine), and while most code is the same, it doesn't use the ELF parser like in Linux.

**Comment by czlhs** [comment]
It would get an empty report result if the `target-directory` ( fileName.hash) didn't exist or the `coverage.db` is empty.  How about throw an error when that happen ?

**Comment by SimonKagstrom** [comment]
This has been merged to main, so closing!

I've added a check for non-existing target-directory as you suggested, which reports an error if it happens. The coverage.db empty isn't checked, but slightly more work to add.
