### ISSUE TITLE
continuous integration: Move to (or try) github actions

### ISSUE THREAD

**Issue by SimonKagstrom** [SimonKagstrom/kcov#345]
Would perhaps indirectly solve #344, assuming it's easier to setup with github actions.

It might also be possible to run CI tests on FreeBSD then, via https://github.com/marketplace/actions/freebsd-vm.

Todo:

- [x] Unit test builds
- [x] OSX builds
- [x] FreeBSD build
- [x] Build the testsuite
- [x] Run the test suite
- [x] Split the test suite with fewer tests for non-x86 archs
- [x] Codecov.io

Coveralls now handled in #346. Unit tests postponed until #348.

**Comment by rollbear** [comment]
FWIW, i just began making the move, and got Apple/Clang building just minutes ago. My setup is unnecessarily complex, a nice one is available here: https://github.com/Dobiasd/FunctionalPlus/blob/master/.github/workflows/ci.yml

Mine, should you want to look, is here: https://github.com/rollbear/trompeloeil/tree/try_github_actions/.github/workflows

**Comment by SimonKagstrom** [comment]
Yes, I saw that. That's actually the direct reason for creating this issue, don't want to be left out of the in-crowd :-)

Thanks for the example! I looked at your config first, but as you say it seems complex :-)

**Comment by rollbear** [comment]
I'm working on gradually removing complications while also adding functionality. It may become useful as a template some time in the future, but currently it's messy.

Let me know when you're reporting coverage to coveralls.io ;-)

**Comment by SimonKagstrom** [comment]
Actually, @l3laze added support for github actions before, so I guess the work left to do is to add the testsuite and FreeBSD and then publish coverage etc via that path.

I'll admit I forgot about that, being ignorant about github actions until @rollbear started using it :-)
