### ISSUE TITLE
Broken URLs in HTML coverage reports (unclickable links) due to unencoded special characters

### ISSUE THREAD

**Issue by jnd-au** [SimonKagstrom/kcov#353]
URL percent encoding is required for standards compliance (e.g. RFC 3986), otherwise links are broken for users in some contexts, like special characters in paths and punctuation like spaces and brackets [ and ]. Handlebars doesn’t provide this type of escaping, so perhaps it should be done when writing the “link” value into .js files (`linkName.c_str()`): https://github.com/SimonKagstrom/kcov/blob/fe83dbf/src/writers/html-writer.cc#L320-L327

libcurl provides a URL string encoding function: https://curl.se/libcurl/c/curl_easy_escape.html

For example, the JS file should have `"link": "src%20%5Bspecfiles%5D/index.html"` (instead of `"link": "src [specfiles]/index.html"`). One wrinkle (and why Handlebars probably cannot solve this anyway) is that the slash in /index.html needs to stay unencoded in this special case, to behave as a path separator (i.e. `%2Findex.html` would not work).

**Comment by SimonKagstrom** [comment]
OK, thanks for the note and the implementation sketch!

I'm very much a newbie when it comes to web technology, so I haven't even though of things like this. Having it in libcurl is good since it's used anyway by kcov.

**Comment by SimonKagstrom** [comment]
Fixed with aa46032 (I hope!).

Thanks for the detailed instructions!
