### ISSUE TITLE
Please update docker image

### ISSUE THREAD

**Issue by kruton** [SimonKagstrom/kcov#367]
The docker image is still using Debian 8 (jessie) which is out of support. Please rebuild the docker container on DockerHub to use a newer version of Debian for which "apt-get" still works.

**Comment by SimonKagstrom** [comment]
Sorry for not replying until now.

**Comment by kruton** [comment]
You could switch the docker image to being put on GitHub to simplify matters. I have a [workflow file that uploads to GitHub packages](https://github.com/kruton/dukkys-bot-rs/blob/main/.github/workflows/main.yml) if you want to check that one out.

The only annoying part is that only Personal Access Tokens (PATs) are supported to login to GitHub Packages. You'd go to Settings > Developer Settings > Personal Access Tokens and create a new token. Make one with `write:packages` and `delete:packages` permissions. Selecting write packages automatically selects “Full Control Of Repositories,” which you have to uncheck.

Store that token in a Settings > Secret in the project named `CR_PAT` and you can use something similar to my GitHub Action linked above.

**Comment by kruton** [comment]
Oh, nevermind.. it looks like they might have solved that issue according to [GitHub docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry).

**Comment by kruton** [comment]
See also the [GitHub documentation on publishing a package using an action](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action).

**Comment by SimonKagstrom** [comment]
OK, it seems that most of the automated builds no longer work, including the docker image ones.

I guess it's time for some cleanup and investigation on how to build using your github actions instead.

**Comment by SimonKagstrom** [comment]
I've updated the image for the "latest" tag now with Bullseye instead, although it's manually built and tagged.

**Comment by SimonKagstrom** [comment]
The docker images should now be built using github actions, so closing this. Thanks for the help!
