### ISSUE TITLE
Not able to install kcov on Docker image.

### ISSUE THREAD

**Issue by NetraPK** [SimonKagstrom/kcov#370]
I am using "golang" image.

Dockerfile:

FROM golang:latest
RUN apt-get update -y && \
    apt-get install -y kcov

Error:
#5 4.928 E: Unable to locate package kcov

When I use the repo it give me below error:
#11 1.184 -- Found Threads: TRUE  
#11 1.188 CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
#11 1.188   The package name passed to `find_package_handle_standard_args` (LIBBFD)
#11 1.188   does not match the name of the calling package (Bfd).  This can lead to
#11 1.188   problems in calling code that expects `find_package` result variables
#11 1.188   (e.g., `_FOUND`) to follow a certain pattern.
#11 1.188 Call Stack (most recent call first):
#11 1.188   cmake/FindBfd.cmake:79 (find_package_handle_standard_args)
#11 1.188   src/CMakeLists.txt:3 (find_package)
#11 1.188 This warning is for project developers.  Use -Wno-dev to suppress it.
#11 1.188 
#11 1.189 -- Found LIBBFD: /usr/lib/x86_64-linux-gnu/libbfd.so  
#11 1.225 -- Target architectures: x86_64
#11 1.236 -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
#11 1.303 -- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.74.0")  
#11 1.304 -- Found DL: /usr/lib/x86_64-linux-gnu/libdl.so
#11 1.305 -- Found M: /usr/lib/x86_64-linux-gnu/libm.so
#11 1.305 -- Found Git: /usr/bin/git
#11 1.309 -- kcov version: v40-2-g80bc
#11 1.324 CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
#11 1.324   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
#11 1.324   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
#11 1.324   OPENSSL_INCLUDE_DIR)
#11 1.324 Call Stack (most recent call first):
#11 1.324   /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
#11 1.324   /usr/share/cmake-3.18/Modules/FindOpenSSL.cmake:486 (find_package_handle_standard_args)
#11 1.324   src/CMakeLists.txt:129 (find_package)
#11 1.324 
#11 1.324 
#11 1.325 -- Configuring incomplete, errors occurred!
#11 1.325 See also "/go/kcov/build/CMakeFiles/CMakeOutput.log".
#11 1.325 See also "/go/kcov/build/CMakeFiles/CMakeError.log".

**Comment by SimonKagstrom** [comment]
It looks like libssl is missing from the build logs?
