### ISSUE TITLE
Docker file is not building an image

### ISSUE THREAD

**Issue by NetraPK** [SimonKagstrom/kcov#373]
Hi ,
I am using the docker file given in Master branch. But whenever I am trying to build it it is giving me following error:
<img width="1319" alt="Screenshot 2022-03-09 at 9 02 22 PM" src="https://user-images.githubusercontent.com/89068241/157474356-2aa7c03f-cf68-40b3-8afc-d57ca579c157.png">

I have a Dockerfile and base image is "ubuntu:21.10". I want to install kcov on top of it..
please guide.

**Comment by SimonKagstrom** [comment]
Are you running it in the kcov directory?

**Comment by NetraPK** [comment]
No I just copied the docker file!!! my bad.. It is working now.

I am trying below but facing the error.:
Docker file:
`FROM debian:bullseye-slim AS builder

RUN apt-get update && \
    apt-get install -y \
        binutils-dev \
        build-essential \
        cmake \
        git \
        libcurl4-openssl-dev \
        libdw-dev \
        libiberty-dev \
    libssl-dev \
        ninja-build \
        python3 \
        zlib1g-dev \
        ;
    
RUN git clone https://github.com/SimonKagstrom/kcov.git && \
    cd kcov/src && \
    mkdir build && \
    cmake -G 'Ninja' .. && \
    cmake --build . && \
    cmake --build . --target install

FROM ubuntu:21.10


# Install Helm
RUN curl -Lo helm-${HELM_VERSION}-linux-amd64.tar.gz "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" && \
    tar -zxvf helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm
RUN apt-get update && \
    apt-get install -y \
        binutils \
        libcurl4 \
        libdw1 \
        zlib1g \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/kcov* /usr/local/bin/
COPY --from=builder /usr/local/share/doc/kcov /usr/local/share/doc/kcov

CMD ["/usr/local/bin/kcov"]

`

The image is getting build. I created the kubernetes pod and exec into it to check kcov is working it gives me below error:
<img width="1605" alt="Screenshot 2022-03-10 at 10 12 53 AM" src="https://user-images.githubusercontent.com/89068241/157591101-2494789a-fd9d-46c3-9e76-136b9d69a77b.png">

**Comment by SimonKagstrom** [comment]
libopcode is something I believe is in binutils, but perhaps the version is different in ubuntu21.10 which is used  in your image?

Perhaps you could just modify the kcov Dockerfile to build with ubuntu:21.10 as well?

**Comment by NetraPK** [comment]
Yes!! Did the same and it is working..
Thank you for your help.
