### ISSUE TITLE
OSX: Code covered: NaN% -

### ISSUE THREAD

**Issue by wop55** [SimonKagstrom/kcov#379]
Compiled a test program:
gcc main.c -o hello

The program is a small main function with some if statements depending on argv.

running:
../kcov /tmp ./hello 1 2 3 4

the generated index.html file says that 0 lines instrumented, and NAN coverage was generated.

What am I missing?

**Comment by SimonKagstrom** [comment]
You'll need debug symbols, so try compiling with

```gcc -g main.c -o hello```
