### ISSUE TITLE
build failure against `binutils-2.39` (`init_disassemble_info()` API change)

### ISSUE THREAD

**Issue by trofi** [SimonKagstrom/kcov#381]
`binutils-2.39` slightly changed an API of `init_disassemble_info()` by adding extra param. Now `kcov` fils the build as:

```
kcov> /build/source/src/parsers/bfd-disassembler.cc: In constructor 'BfdDisassembler::BfdDisassembler()':
kcov> /build/source/src/parsers/bfd-disassembler.cc:78:38: error: too few arguments to function 'void init_disassemble_info(disassemble_info*, void*, fprintf_ftype, fprintf_styled_ftype)'
kcov>    78 |                 init_disassemble_info(&m_info, (void *)this, BfdDisassembler::opcodesFprintFuncStatic);
kcov>       |                 ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If it helps here is how `linux.git` dealt with API change: https://github.com/torvalds/linux/compare/00b32625982e0c796f0abb8effcac9c05ef55bd3...600b7b26c07a070d0153daa76b3806c1e52c9e00

**Comment by SimonKagstrom** [comment]
Thanks for the report!

I'll think of some way to handle both, although I guess in kcovs case if might be enough with just an #ifdef

**Comment by SimonKagstrom** [comment]
Fixed by @oreo639 , so closing!
