### ISSUE TITLE
bash coverage problems with for loops and while

### ISSUE THREAD

**Issue by sschmid** [SimonKagstrom/kcov#387]
Hi @SimonKagstrom,

I hope you're doing well.

I ran into issues where certain lines being reported as not covered when using kcov, bash and bats.
I extracted samples to reproduce:
- https://github.com/sschmid/kcov-coverage

I attached the coverage report to the kcov-coverage GitHub action artifacts:
- https://github.com/sschmid/kcov-coverage/actions/runs/3297654343

```sh
main() {
  while read -r i; do
    echo -n "-$i"
  done < <(seq 1 3)     # not covered
}

while read -r i; do
  echo -n "-$i"
done < <(seq 1 3)       # covered

main
```

<img width="553" alt="Screen Shot 2022-10-21 at 16 35 03" src="https://user-images.githubusercontent.com/233700/197221618-9fab284a-c85d-4b52-8685-c2e35398134a.png">

The kcov-coverage sample also includes for loops which are covered as expected.
In my actual project they are not.

example 1: https://coveralls.io/builds/53486336/source?filename=src%2Fbee-run.bash#L147
example 2: https://coveralls.io/builds/53486336/source?filename=src%2Fbee-run.bash#L155

When scolling through the report you will find multiple locations where for or while loops are not covered.

This is how I use kcov: see GitHub action ci.yml
https://github.com/sschmid/kcov-coverage/blob/main/.github/workflows/ci.yml

Do you have an idea what is going on or how I can fix this?

**Comment by sschmid** [comment]
As a workaround, I excluded those patterns with `--exclude-line`.
```
kcov --include-path=src --exclude-line='done <,for' /__w/bee/bee/coverage test/bats/bin/bats test
```

While not solving the underlying issue, it's good enough for me 👍

**Comment by SimonKagstrom** [comment]
That's an option I didn't even remember existed :-)
