### ISSUE TITLE
Are there any ways to set Kcov that scan only specified .so file or library?

### ISSUE THREAD

**Issue by sampad1370** [SimonKagstrom/kcov#394]
Hello

Thanks for good tools and I think it's very useful.

I want to only kcov scan my library and skip others, how?

Thanks.

**Comment by SimonKagstrom** [comment]
An easy way, but not directly tied to shared libraries, is to filter for
patterns or paths for source files.

E.g., if two libraries are in

projects/graphics and work/network

You can invoke kcov with --include-pattern=graphics,network

To filter out source files with this pattern in the file name.
--include-path can be used if you want an exact path to include. Similarly
--exclude-pattern is also possible.

**Comment by sampad1370** [comment]
@SimonKagstrom
Thank you, I got it.
I appreciate for your describing in details, and I fixed my problem with using your suggestion to use --include-pattern.
