### ISSUE TITLE
no code coverage for lines after commands like "Z=`a <<$PATH`" or setting PS4 variable

### ISSUE THREAD

**Issue by ChetanSheelwant** [SimonKagstrom/kcov#44]
Hi Simon,

I have a simple shell script which sources a env file and prints and the i am not able to get the code coverage for the lines after the following 2 lines were executed.
1. If a input re-direction sing is used like "CURR_PATH=`a << $PATH`"
2. If the shell prompt variable is set like 
PS4_FORMAT=' \D{%Y%m%d-%k:%M:%S}$(printf " %-20s:%-4d" ${BASH_SOURCE##*/} ${LINENO}):'
export PS4="$PS4_FORMAT"

Contents of scripts
[
chetan_clust_1_01:~ # cat 1.env
# !/bin/bash

PRIVPORTS="0:1023"
SSH_PORT=22
SMTP_PORT=25

CURR_PATH=`a << $PATH` 2>/dev/null
echo $CURR_PATH

PS4_FORMAT=' \D{%Y%m%d-%k:%M:%S}$(printf " %-20s:%-4d" ${BASH_SOURCE##*/} ${LINENO}): '
export PS4="$PS4_FORMAT"

DHCP_PORTS=67:68
TFTP_PORT=69
HTTP_PORT_PRIV=8080

chetan_clust_1_01:~ # cat 1.sh
# !/bin/bash

. ./1.env
echo "hello" 2>/dev/null
CURR_PATH=`pwd`
export MY_PATH="$CURR_PATH"
echo "world"
chetan_clust_1_01:~ #

]

Can you please help me to identify what could be the issue. Attaching the code coverage snapshots for each of the 2 cases

![issue_1](https://cloud.githubusercontent.com/assets/10196154/5454798/a7089f1c-855b-11e4-9345-744a8fc04920.jpg)
![issue_2](https://cloud.githubusercontent.com/assets/10196154/5454813/b3bbbd16-855b-11e4-813e-5e2f9ccb8a55.jpg)

Thanks and Regards
Chetan

**Comment by iwonbigbro** [comment]
Is kcov still using PS4 for tracing?  If so, you may want to consider using a tracer function instead, via the DEBUG trap.  This will avoid problems with buffer length limits within bash and scenarios where scripts set PS4 for the -x option (very common).

**Comment by SimonKagstrom** [comment]
Indeed it is! I didn't even know about the DEBUG trap, will look into that. Thanks!

**Comment by SimonKagstrom** [comment]
I've now pushed a new option which allows using the DEBUG trap for collection. It doesn't work for quite all cases yet (?), so it's default off for now. Thanks though!
