### ISSUE TITLE
Docker Sponsored OSS

### ISSUE THREAD

**Issue by williamdes** [SimonKagstrom/kcov#449]
You should enroll into Sponsored OSS at Docker: https://www.docker.com/community/open-source/application/

It will show a badge on the image like: https://hub.docker.com/r/shellspec/kcov/tags
And show up "first" in results: https://hub.docker.com/search?q=kcov

**Comment by SimonKagstrom** [comment]
Sounds like a good idea! However, I looked at the application page, but it appears that GPLv2 isn't available as a distribution license, which surprised me.

Moving to GPLv3 really isn't an option, since there are users which aren't allowed to use v3-licensed software.

**Comment by williamdes** [comment]
> Sounds like a good idea! However, I looked at the application page, but it appears that GPLv2 isn't available as a distribution license, which surprised me.

Is there an "Other" option ?

**Comment by SimonKagstrom** [comment]
No, doesn't seem like that unfortunately. Kind of strange I must say.

**Comment by SimonKagstrom** [comment]
Having seen that reminds me to move my other project to MIT for now, until I've got any real contributions from other people :-)

**Comment by SimonKagstrom** [comment]
Yeah, I did that and applied.

Thanks for bringing this up. Didn't know about  this program before.
