### ISSUE TITLE
Feature request: --report-format=xml,json,vendorName

### ISSUE THREAD

**Issue by williamdes** [SimonKagstrom/kcov#453]
It could be nice to filter the type of report to produce, this would save some computing time

What do you think ?

**Comment by SimonKagstrom** [comment]
There's --cobertura-only, which I use for vscode (see doc/vscode.md), but nothing in general.

I think the main advantage is less clutter, since performance is typically dominated by the breakpoints anyway.

**Comment by williamdes** [comment]
Could we have an option to not have the .so files and html stuff ?
Only report files (xml/json)

**Comment by williamdes** [comment]
> Anyway, I think your feature makes sense, and --cobertura-only would then be a special case meaning the same thing as --report-format=xml.

Good idea
Is there only one output format ?
Maybe they should be documented because I could not figure it out myself :)

**Comment by SimonKagstrom** [comment]
> > Anyway, I think your feature makes sense, and --cobertura-only would then be a special case meaning the same thing as --report-format=xml.
> 
> Good idea Is there only one output format ? Maybe they should be documented because I could not figure it out myself :)

Yes, there are 6 in total. They are documented via the README, but for now they have all always been written so no specific options (except for coveralls-only, which is mainly for vscode).
