### ISSUE TITLE
Python script end of line

### ISSUE THREAD

**Issue by BenoitAmbry** [SimonKagstrom/kcov#463]
Looks like the python script is not in unix format and it breaks the build on my ubuntu box with
/usr/bin/env: ‘python3\r’: No such file or directory/usr/bin/env:
Running dos2unix of that file fixes the build.

**Comment by SimonKagstrom** [comment]
Does it run fine with regular Python?

Not really sure where the issue comes from. I thought it would be some hardcoded `/usr/bin/env python\n` in kcov, but I can't find it.

**Comment by BenoitAmbry** [comment]
The issue is your python scripts src/bin-to-c-source.py.
Looks like running `git config core.autocrlf input` fixed the issue for me, but I usually do not need to do this on other projects.
