### ISSUE TITLE
Build fails in newly forked repository

### ISSUE THREAD

**Issue by jack-rann** [SimonKagstrom/kcov#465]
I recently forked the `kcov` repository and attempted to trigger the CI workflow.  This failed on all runners with the following error:

```  -- The C compiler identification is GNU 11.4.0
  -- The CXX compiler identification is GNU 11.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Git: /usr/bin/git
  fatal: No names found, cannot describe anything.
  -- kcov version: 
  CMake Error at CMakeLists.txt:39 (string):
    string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
    command.
```

The issue appears to be that forked repositories do not contain any tags from the parent repository, thus `CMakeLists.txt` cannot successfully execute `git describe --abbrev=4 --tags HEAD` to determine the version number.  The code to parse the version number from the `ChangeLog` file is never executed (as it exists in the `else` clause).

Creating a dummy `v0` tag and pushing it to the forked repository appears allow all workflow runners to succeed.

**Comment by SimonKagstrom** [comment]
Ah, thanks! That explains it.

I've pushed a small fix, which at least locally appears to work.
