### ISSUE TITLE
Failed to parse dwarf file generated on Mac sequoia

### ISSUE THREAD

**Issue by myzhan** [SimonKagstrom/kcov#468]
I think it's an issue of libdwarf, but kcov is also affected.

See also: https://github.com/davea42/libdwarf-code/issues/269

**Comment by SimonKagstrom** [comment]
OK, thanks for the info! Sounds like libdwarf has made progress on it, so hopefully should be fixed with a later release.

I'm regularly using kcov on sequoia, but I suppose it might depend on compiler options etc?

**Comment by myzhan** [comment]
Fixed in libdwarf.

**Comment by SimonKagstrom** [comment]
Great, thanks!

**Comment by SimonKagstrom** [comment]
Strangely it has worked all the time on my M1 Macbook Air, but good to hear it's fixed upstream! Hopefully a release of libdwarf can be done soon, and as soon as it's in homebrew this should be good for everyone.

**Comment by myzhan** [comment]
I'm using Sequoia 15.5, and kcov reports no errors but get no coverage.

```bash
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by SimonKagstrom** [comment]
Thanks for testing! Then it looks like a new regression unfortunately, so #485 will have to be fixed. Seems to be on the dwarf level just as this issue.
