### ISSUE TITLE
Basic usage of the tooling

### ISSUE THREAD

**Issue by brunolnetto** [SimonKagstrom/kcov#469]
Hi,

I would like to use tool `kcov` on my daily shell script activities. For that, I created a minimal example like below on the same folder. Then, ran the command `kcov ./coverage-report ./test_example.sh` followed by `xdg-open coverage-report/index.html`. The coverage is very low, ~6%, which is not as I expected. How should I proceed to obtain the 100% coverage rate I expected for such a simple example?

`example.sh`:
```
#!/bin/bash

# Function to add two numbers
add_numbers() {
    local num1=$1
    local num2=$2
    echo $((num1 + num2))
}

# Function to subtract two numbers
subtract_numbers() {
    local num1=$1
    local num2=$2
    echo $((num1 - num2))
}
```

`test_example.sh`:
```
#!/bin/bash

# Source the original script to test
source ./example.sh

# Test for add_numbers function
test_add_numbers() {
    result=$(add_numbers 2 3)
    assertEquals "Expected 2 + 3 to be 5" 5 "$result"
}

# Test for subtract_numbers function
test_subtract_numbers() {
    result=$(subtract_numbers 5 2)
    assertEquals "Expected 5 - 2 to be 3" 3 "$result"
}
```

**Comment by SimonKagstrom** [comment]
In this example, it might be because kcov looks for shell files in the shell script directory. That can be turned off by `--bash-dont-parse-binary-dir`. Alternatively (or also), you can filter interesting files by either `--include-pattern=XXX`, `--include-path=XXX`.

In your example, you could do

```
kcov --include-pattern=example.sh <the other kcov options you used before>
```

**Comment by brunolnetto** [comment]
I ran as you say, below. However, I am still getting some weird behavior. Do you recommend we investigating further?

1. `kcov --bash-dont-parse-binary-dir ./coverage-report ./test_example.sh`;
2. `kcov --include-pattern=example.sh ./coverage-report ./test_example.sh`.

**Comment by SimonKagstrom** [comment]
but are the lines covered as expected in example.sh? I.e., is the total coverage more reasonable this way?

The shell parser is imperfect in the way that it sometimes considers non-code lines as code, and the other way around

**Comment by brunolnetto** [comment]
It has not improved substantially. I opted to used `bashcov` with `bats` instead. I hope, you do not feel sad for that. Check it out: https://github.com/whosbash/example-kcov

**Comment by SimonKagstrom** [comment]
No problem at all! Always best to use the tool that works for you!

However, when testing your example, I think the problem is that you aren't running bats, so none of the tests are being executed. At least I think the 6% coverage report looks correct - since the tests aren't actually being run.
