### ISSUE TITLE
kcov trying to read non existent files.

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [SimonKagstrom/kcov#65]
Hi, again,

We have some shell script code which sources in a dynamically generated file when it runs. To test it the unittest script simply creates a dummy file to be sourced from within a test directory. When the test complets the directory (and the dynamic file) is deleted.

The test itself is a Python unittest script, so it runs many different tests, all of which (currently) write to the same kcov output directory for that  testrun, so that we can accumulate test results for the entire file being tested.

If I start with an empty kcov_out directory and run one test it passes. However, if I run the entire test script the first test passes, but all subsequent tests fail because kcov reports this error and returns a failure exit status:
````
kcov: error: File /tmp/test_dir/file.dat exists, but can't be read???
````
I can reproduce this with the following test script and command sequence:
````
% cat test.sh
#!/bin/bash
test -f file.dat &&
    source file.dat
rm -f file.dat

% echo -e "some_var=some_value\n" > file.dat
% kcov /tmp/kcov_out ./test.sh
% kcov /tmp/kcov_out ./test.sh
kcov: error: File /tmp/test_dir/file.dat exists, but can't be read???
````
I tried excluding this file with --exclude-pattern=file.dat, and that seemed to work, but using --exclude-pattern='*.dat' did not work.

So, two things:
1. Is there a better way to make kcov not complain about files in its database that are no longer present? (Could the error message be phrased better? Ie, 'File ... previously checked but can no longer be found'.)
2. Does the --exclude-pattern use patterns other than filename metacharacters, or does it not use patterns?

**Comment by SimonKagstrom** [comment]
It's from the merge-file-parser.cc, which does a panic if the file doesn't exist.

That's not reasonable, and I'll change it to just ignore those files. Thanks for the detailed report!

**Comment by SimonKagstrom** [comment]
Commit 9b3c7c2 handles the case you describe above. The panic is still there, but will now get triggered if the file exists, but has been made unreadable.

**Comment by SimonKagstrom** [comment]
As for --exclude-pattern and --include-pattern, they use a simple string compare, so basically with

```
kcov --exclude-pattern=dummy /tmp/kcov script
```

every path which contains the string "dummy" will be excluded from the output. There is also --include-path and --exclude-path which uses actual filesystem paths.

**Comment by Mark-E-Hamilton** [comment]
Wow, thanks again. I feel bad having you got to sleep with issues from me, and then waking up with more. Eventually I'll slow down, of course. ;)

**Comment by SimonKagstrom** [comment]
No problem! Your bug reports are generally quite easy to follow, since they typically have good example scripts attached - so that's appreciated.
