### ISSUE TITLE
kcov: Process exited with signal 11

### ISSUE THREAD

**Issue by anirudhrudr** [SimonKagstrom/kcov#71]
I was trying semaphore to synchronize the multiple thread using c. 
And tried executing it with kcov.

Below is the code I was trying to execute with kcov:

	#include <stdio.h> 
	#include <unistd.h>
	#include <stdlib.h>
	#include <string.h>
	#include <pthread.h>
	#include <semaphore.h>
	void *thread_function(void *arg);
	sem_t bin_sem;
	#define WORK_SIZE 1024
	char work_area[WORK_SIZE];
  
	int main() {
		int res;
		pthread_t a_thread;
		void *thread_result;
	
		res = sem_init(&bin_sem, 0, 0);
		if (res != 0) {
			perror("Semaphore initialization failed");
			exit(EXIT_FAILURE);
		}
		res = pthread_create(&a_thread, NULL, thread_function, NULL);
		if (res != 0) {
			perror("Thread creation failed");
			exit(EXIT_FAILURE);
		}
		printf("Input some text. Enter 'end' to finish\n");
		while(strncmp("end", work_area, 3) != 0) {
			fgets(work_area, WORK_SIZE, stdin);
			sem_post(&bin_sem);
		}
		printf("\nWaiting for thread to finish...\n");
		res = pthread_join(a_thread, &thread_result);
		if (res != 0) {
			perror("Thread join failed");
			exit(EXIT_FAILURE);
		}
		printf("Thread joined\n");
		sem_destroy(&bin_sem);
		exit(EXIT_SUCCESS);
	}
	
	void *thread_function(void *arg) {
		sem_wait(&bin_sem);
		while(strncmp("end", work_area, 3) != 0) {
			printf("You input %d characters\n", strlen(work_area) -1);
			sem_wait(&bin_sem);
		}
		pthread_exit(NULL);
	}  

When I try to run above code with kcov by 

 'kcov /tmp/sema/ /tmp/semaphore'

I get the following error

  kcov: error: Cannot open linux-vdso32.so.1

  Input some text. Enter 'end' to finish
  kcov: Process exited with signal 11 (SIGSEGV) at 0x0

And there is no coverage generated.

But, It works fine without kcov.

**Comment by SimonKagstrom** [comment]
I can't reproduce this, the program works fine for me under kcov in both 32- and 64-bit mode.

This error,

```
  kcov: error: Cannot open linux-vdso32.so.1
```

indicates that you're running a 32-bit kcov on a 64-bit machine (and that your program is a 32-bit binary. Is this correct? What version of kcov are you running? Did you compile your application with -g to generate debug information? (newer versions of kcov should warn if you didn't)

**Comment by anirudhrudr** [comment]
Thanks for your reply.
I tried this in on 32 bit powerpc target and faced above issue.
I'll try this on x86 pc, just to make sure that its my target issue.

**Comment by SimonKagstrom** [comment]
Ah, OK. I can reproduce it then in an emulator.

The reason seems to be that the powerpc reports some breakpoints which can't be found. Because of the dlopen handling (and shared libraries in general), kcov will special-case these. I don't know why this application would generate more of these, but if you want to work around it, you could try the following patch,

```
diff --git a/src/engines/ptrace.cc b/src/engines/ptrace.cc
index 3524033..3f857a1 100644
--- a/src/engines/ptrace.cc
+++ b/src/engines/ptrace.cc
@@ -678,6 +678,7 @@ private:
        // Skip over this instruction
        void skipInstruction()
        {
+               return;
                // Nop on x86, op on PowerPC/ARM
 #if defined(__powerpc__) || defined(__arm__)
                unsigned long regs[1024];
```

and run kcov without solibs, i.e.,

```
kcov --skip-solibs /tmp/kcov /path/to/your/application
```

**Comment by SimonKagstrom** [comment]
I found what the problem is on PowerPC, and commit b296deb fixes this issue.

**Comment by anirudhrudr** [comment]
Thanks Simon :+1: 

I tested the commit and I get no error as earlier.

However, I don't see any coverage as well.
Please see the execution logs below:

	root@anirudh_lappy:~# kcov /tmp/kcov/sema /tmp/semaphore  
	kcov: error: Cannot open linux-vdso32.so.1
	
	Input some text. Enter 'end' to finish
	hello
	You input 5 characters
	how
	You input 3 characters
	are
	You input 3 characters
	you
	You input 3 characters
	bye
	You input 3 characters
	end
	
	Waiting for thread to finish...
	Thread joined
	root@anirudh_lappy:~#
	root@anirudh_lappy:~# cat /tmp/kcov/sema/index.json 
	var data = {files:[
	{"link":"semaphore/index.html","title":"semaphore","summary_name":"semaphore","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"0","total_lines" : "0"},
	], merged_files:[]};
	var percent_low = 25;var percent_high = 75;
	var header = { "command" : "semaphore", "date" : "2015-03-08 19:52:50", "instrumented" : 0, "covered" : 0,};
	root@anirudh_lappy:~#
	root@anirudh_lappy:~#
	root@anirudh_lappy:~# kcov --skip-solibs /tmp/kcov/sema/ /tmp/semaphore 
	Input some text. Enter 'end' to finish
	hi
	You input 2 characters
	hello
	You input 5 characters
	end
	
	Waiting for thread to finish...
	Thread joined
	root@anirudh_lappy:~# cat /tmp/kcov/sema/index.json 
	var data = {files:[
	{"link":"semaphore/index.html","title":"semaphore","summary_name":"semaphore","covered_class":"lineNoCov","covered":"0.0","covered_lines":"0","uncovered_lines":"0","total_lines" : "0"},
	], merged_files:[]};
	var percent_low = 25;var percent_high = 75;
	var header = { "command" : "semaphore", "date" : "2015-03-08 19:55:06", "instrumented" : 0, "covered" : 0,};
	root@anirudh_lappy:~#

**Comment by SimonKagstrom** [comment]
Did you compile with -g? I tested your application and got coverage from
it. I didn't are the .so error message on PowerPC either though.

**Comment by anirudhrudr** [comment]
I did compile with it with -g.
I Initially skipped the --skip-solibs so got .so error. 
I will check with my other applications as well, I suppose some issue with my compilation itself.

**Comment by SimonKagstrom** [comment]
Do you have the source code on the machine you run on? Otherwise you can always run in collect/report mode, i.e.,

```
kcov --collect-only /tmp/kcov your-app
scp -r /tmp/kcov <machine-with-source-code>:/tmp/kcov
```

and then on the machine where the source code resides

```
kcov --report-only /tmp/kcov
```

**Comment by SimonKagstrom** [comment]
You can also try running with --debug=15 to see what kcov does (debug output of e.g., breakpoint setting).
