### ISSUE TITLE
kcov crashes with very short executable name

### ISSUE THREAD

**Issue by lifthrasiir** [SimonKagstrom/kcov#72]
```
$ echo 'int main() {}' > t.c
$ gcc t.c -o t -g
$ kcov out t
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551614) > this->size() (which is 1)
Aborted
```

One- or two-letter-long executables are affected. `BashEngine::matchParser` and others do not work correctly with them.

**Comment by SimonKagstrom** [comment]
Thanks for the fix, I've merged your pull request!

I added a regression test in c71c5c1 that hopefully should validate your fix from now on.
