### ISSUE TITLE
kcov multi-line strings not covered.

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [SimonKagstrom/kcov#76]
This might be related to a previous issue, but I have (again) a simple test script
````
#!/bin/bash
MESSAGE="some message"
USAGE="usage: some message

   --some-option   Does something
"
NOOP=
````
Should be 100% covered, but I only get 60%.  The entire USAGE assignment, except for the last quote, is marked as uncoverd (red.)

**Comment by SimonKagstrom** [comment]
Fixed in 32dc9f4.

Bash confusingly marks the last quote-line as executed in this case, so kcov follows that pattern.
