### ISSUE TITLE
Server mode: Running kcov on a target system without debug symbols

### ISSUE THREAD

**Issue by SimonKagstrom** [SimonKagstrom/kcov#92]
On a target system, there are typically no debug symbols in binaries. Kcov won't be able to collect data in these cases, which is unfortunate. An idea is therefore to run it in "server mode", where kcov first sets up a database of breakpoints on the build system:

```
kcov --create-breakpoint-database /tmp/kcov-database /path/to/sysroot
scp -r /tmp/kcov-database <target-system>:/tmp/
```

and then on the target system uses this database

```
kcov --breakpoint-database=/tmp/kcov-database /tmp/kcov <program-to-run>
```

--collect-only will be implicit for this option.

Seccomp might be useful: http://www.cs.technion.ac.il/~nimi/

**Comment by kaspar030** [comment]
Once this is implemented, would it be possible to attach to an executable using gdbserver?
This would be a breakthrough for embedded systems that can't afford the instrumentation that gcov requires.

**Comment by SimonKagstrom** [comment]
Well, the idea is to use something similar to gdbserver, i.e., a smaller executable which together with a symbol database can be used to collect coverage info from binaries without symbols.

The work on this is somewhat stalled, but I plan on continuing with it sometime this fall.

**Comment by SimonKagstrom** [comment]
Fixed with

e43715bd4a658f8fafbfde31cbb7d6081ed69da1

some kinks will be handled in other issues.
